// Code generated by gen-holidays from definitions/be_fr.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("be_fr", func() {
	DescribeTable("000_JourDeLAn", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Jour de l'an")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jour de l'an", hols))
	},
		Entry("2007-01-01", "2007-01-01"),
	)

	DescribeTable("001_Pâques", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Pâques")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pâques", hols))
	},
		Entry("2007-04-08", "2007-04-08"),
	)

	DescribeTable("002_LundiDePâques", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Lundi de Pâques")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi de Pâques", hols))
	},
		Entry("2007-04-09", "2007-04-09"),
	)

	DescribeTable("003_FêteDuTravail", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fête du travail")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête du travail", hols))
	},
		Entry("2007-05-01", "2007-05-01"),
	)

	DescribeTable("004_Ascension", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ascension")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ascension", hols))
	},
		Entry("2007-05-17", "2007-05-17"),
	)

	DescribeTable("005_Pentecôte", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Pentecôte")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pentecôte", hols))
	},
		Entry("2007-05-27", "2007-05-27"),
	)

	DescribeTable("006_LundiDePentecôte", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Lundi de Pentecôte")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi de Pentecôte", hols))
	},
		Entry("2007-05-28", "2007-05-28"),
	)

	DescribeTable("007_FêteNationale", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fête nationale")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête nationale", hols))
	},
		Entry("2007-07-21", "2007-07-21"),
	)

	DescribeTable("008_Assomption", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Assomption")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Assomption", hols))
	},
		Entry("2007-08-15", "2007-08-15"),
	)

	DescribeTable("009_Toussaint", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Toussaint")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Toussaint", hols))
	},
		Entry("2007-11-01", "2007-11-01"),
	)

	DescribeTable("010_Armistice1918", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Armistice 1918")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Armistice 1918", hols))
	},
		Entry("2007-11-11", "2007-11-11"),
	)

	DescribeTable("011_Noël", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Noël")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Noël", hols))
	},
		Entry("2007-12-25", "2007-12-25"),
	)

	DescribeTable("012_Pâques", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Pâques")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pâques", hols))
	},
		Entry("2017-4-16", "2017-4-16"),
	)

	DescribeTable("013_LundiDePâques", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Lundi de Pâques")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi de Pâques", hols))
	},
		Entry("2017-4-17", "2017-4-17"),
	)

	DescribeTable("014_Ascension", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ascension")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ascension", hols))
	},
		Entry("2017-5-25", "2017-5-25"),
	)

	DescribeTable("015_Pentecôte", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Pentecôte")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pentecôte", hols))
	},
		Entry("2017-6-4", "2017-6-4"),
	)

	DescribeTable("016_LundiDePentecôte", func(s string) {
		opts := holidays.Options{Regions: []string{"be_fr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Lundi de Pentecôte")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi de Pentecôte", hols))
	},
		Entry("2017-6-5", "2017-6-5"),
	)

})
