// Code generated by gen-holidays from definitions/by.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var byRules = []definition.HolidayRule{
	{
		Name:         "Вялікдзень каталіцкі",
		Regions:      []string{"by"},
		Month:        0,
		Wday:         -1,
		Function:     "easter",
		FunctionArgs: []string{"year"},
		Type:         definition.Informal,
	},
	{
		Name:         "Вялікдзень праваслаўны",
		Regions:      []string{"by"},
		Month:        0,
		Wday:         -1,
		Function:     "orthodox_easter",
		FunctionArgs: []string{"year"},
		Type:         definition.Informal,
	},
	{
		Name:             "Радуніца",
		Regions:          []string{"by"},
		Month:            0,
		Wday:             -1,
		Function:         "orthodox_easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 9,
	},
	{
		Name:    "Новы год",
		Regions: []string{"by"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Новы год",
		Regions: []string{"by"},
		Month:   1,
		Mday:    2,
		Wday:    -1,
	},
	{
		Name:    "Каляды праваслаўныя",
		Regions: []string{"by"},
		Month:   1,
		Mday:    7,
		Wday:    -1,
	},
	{
		Name:    "Дзень абаронцаў Айчыны і Узброеных Сіл Рэспублікі Беларусь",
		Regions: []string{"by"},
		Month:   2,
		Mday:    23,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Міжнародны жаночы дзень",
		Regions: []string{"by"},
		Month:   3,
		Mday:    8,
		Wday:    -1,
	},
	{
		Name:    "Дзень Канстытуцыі",
		Regions: []string{"by"},
		Month:   3,
		Mday:    15,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Дзень яднання народаў Беларусі і Расіі",
		Regions: []string{"by"},
		Month:   4,
		Mday:    2,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Свята працы",
		Regions: []string{"by"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Дзень Перамогі",
		Regions: []string{"by"},
		Month:   5,
		Mday:    9,
		Wday:    -1,
	},
	{
		Name:    "Дзень Незалежнасці Рэспублікі Беларусь (Дзень Рэспублікі)",
		Regions: []string{"by"},
		Month:   7,
		Mday:    3,
		Wday:    -1,
	},
	{
		Name:    "Дзень народнага адзінства",
		Regions: []string{"by"},
		Month:   9,
		Mday:    17,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Дзяды",
		Regions: []string{"by"},
		Month:   11,
		Mday:    2,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Дзень Кастрычніцкай рэвалюцыі",
		Regions: []string{"by"},
		Month:   11,
		Mday:    7,
		Wday:    -1,
	},
	{
		Name:    "Каляды каталіцкія",
		Regions: []string{"by"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
}

var byRegionNames = map[string]string{
	"by": "Belarus",
}

func init() {
	engine.RegisterCountry("by", byRules)
	engine.RegisterRegionNames("by", byRegionNames)
}
