// Code generated by gen-holidays from definitions/cl.yaml@v9.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var clRules = []definition.HolidayRule{
	{
		Name:             "Viernes Santo",
		Regions:          []string{"cl"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:             "Sábado Santo",
		Regions:          []string{"cl"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -1,
	},
	{
		Name:         "San Pedro y San Pablo",
		Regions:      []string{"cl"},
		Month:        0,
		Wday:         -1,
		Function:     "st_peter_st_paul_cl",
		FunctionArgs: []string{"year"},
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2000}},
		},
	},
	{
		Name:         "Día de las Iglesias Evangélicas y Protestantes",
		Regions:      []string{"cl"},
		Month:        0,
		Wday:         -1,
		Function:     "other_churches_day_cl",
		FunctionArgs: []string{"year"},
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2008}},
		},
	},
	{
		Name:    "Año Nuevo",
		Regions: []string{"cl"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Día del Trabajo",
		Regions: []string{"cl"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Día de las Glorias Navales",
		Regions: []string{"cl"},
		Month:   5,
		Mday:    21,
		Wday:    -1,
	},
	{
		Name:    "San Pedro y San Pablo",
		Regions: []string{"cl"},
		Month:   6,
		Mday:    29,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeUntil, Years: []int{1999}},
		},
	},
	{
		Name:    "Día de la Virgen del Carmen",
		Regions: []string{"cl"},
		Month:   7,
		Mday:    16,
		Wday:    -1,
	},
	{
		Name:    "Asunción de la Virgen",
		Regions: []string{"cl"},
		Month:   8,
		Mday:    15,
		Wday:    -1,
	},
	{
		Name:    "Independencia Nacional",
		Regions: []string{"cl"},
		Month:   9,
		Mday:    18,
		Wday:    -1,
	},
	{
		Name:    "Día de las Glorias del Ejército",
		Regions: []string{"cl"},
		Month:   9,
		Mday:    19,
		Wday:    -1,
	},
	{
		Name:    "Encuentro de Dos Mundos",
		Regions: []string{"cl"},
		Month:   10,
		Mday:    12,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeUntil, Years: []int{1999}},
		},
	},
	{
		Name:         "Encuentro de Dos Mundos",
		Regions:      []string{"cl"},
		Month:        10,
		Wday:         -1,
		Function:     "columbus_day_cl",
		FunctionArgs: []string{"year"},
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2000}},
		},
	},
	{
		Name:    "Día de Todos los Santos",
		Regions: []string{"cl"},
		Month:   11,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Inmaculada Concepción de María",
		Regions: []string{"cl"},
		Month:   12,
		Mday:    8,
		Wday:    -1,
	},
	{
		Name:    "Navidad",
		Regions: []string{"cl"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
}

var clRegionNames = map[string]string{
	"cl": "Chile",
}

func init() {
	engine.RegisterCountry("cl", clRules)
	engine.RegisterRegionNames("cl", clRegionNames)
}
