// Code generated by gen-holidays from definitions/co.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var coRules = []definition.HolidayRule{
	{
		Name:             "Jueves Santo",
		Regions:          []string{"co"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -3,
	},
	{
		Name:             "Viernes Santo",
		Regions:          []string{"co"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:             "Día de la Ascensión",
		Regions:          []string{"co"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 43,
	},
	{
		Name:             "Corpus Christi",
		Regions:          []string{"co"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 64,
	},
	{
		Name:             "Sagrado Corazón",
		Regions:          []string{"co"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 71,
	},
	{
		Name:    "Año Nuevo",
		Regions: []string{"co"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:         "Día de los Reyes Magos",
		Regions:      []string{"co"},
		Month:        1,
		Mday:         6,
		Wday:         -1,
		Function:     "to_following_monday_if_not_monday",
		FunctionArgs: []string{"date"},
	},
	{
		Name:         "Día de San José",
		Regions:      []string{"co"},
		Month:        3,
		Mday:         19,
		Wday:         -1,
		Function:     "to_following_monday_if_not_monday",
		FunctionArgs: []string{"date"},
	},
	{
		Name:    "Día del Trabajo",
		Regions: []string{"co"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:         "San Pedro y San Pablo",
		Regions:      []string{"co"},
		Month:        6,
		Mday:         29,
		Wday:         -1,
		Function:     "to_following_monday_if_not_monday",
		FunctionArgs: []string{"date"},
	},
	{
		Name:         "Día de Nuestra Señora del Rosario de Chiquinquirá",
		Regions:      []string{"co"},
		Month:        7,
		Mday:         9,
		Wday:         -1,
		Function:     "to_following_monday_if_not_monday",
		FunctionArgs: []string{"date"},
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2026}},
		},
	},
	{
		Name:    "Día de la Independencia",
		Regions: []string{"co"},
		Month:   7,
		Mday:    20,
		Wday:    -1,
	},
	{
		Name:    "Batalla de Boyacá",
		Regions: []string{"co"},
		Month:   8,
		Mday:    7,
		Wday:    -1,
	},
	{
		Name:         "La Asunción de la Virgen",
		Regions:      []string{"co"},
		Month:        8,
		Mday:         15,
		Wday:         -1,
		Function:     "to_following_monday_if_not_monday",
		FunctionArgs: []string{"date"},
	},
	{
		Name:         "Día de la Raza",
		Regions:      []string{"co"},
		Month:        10,
		Mday:         12,
		Wday:         -1,
		Function:     "to_following_monday_if_not_monday",
		FunctionArgs: []string{"date"},
	},
	{
		Name:         "Día de Todos los Santos",
		Regions:      []string{"co"},
		Month:        11,
		Mday:         1,
		Wday:         -1,
		Function:     "to_following_monday_if_not_monday",
		FunctionArgs: []string{"date"},
	},
	{
		Name:         "Independencia de Cartagena",
		Regions:      []string{"co"},
		Month:        11,
		Mday:         11,
		Wday:         -1,
		Function:     "to_following_monday_if_not_monday",
		FunctionArgs: []string{"date"},
	},
	{
		Name:    "Día de la Inmaculada Concepción",
		Regions: []string{"co"},
		Month:   12,
		Mday:    8,
		Wday:    -1,
	},
	{
		Name:    "Navidad",
		Regions: []string{"co"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
}

var coRegionNames = map[string]string{
	"co": "Colombia",
}

func init() {
	engine.RegisterCountry("co", coRules)
	engine.RegisterRegionNames("co", coRegionNames)
}
