// Code generated by gen-holidays from definitions/cr.yaml@v9.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var crRules = []definition.HolidayRule{
	{
		Name:             "Jueves Santo",
		Regions:          []string{"cr"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -3,
	},
	{
		Name:             "Viernes Santo",
		Regions:          []string{"cr"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:    "Año Nuevo",
		Regions: []string{"cr"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Día de Juan Santamaría",
		Regions: []string{"cr"},
		Month:   4,
		Mday:    11,
		Wday:    -1,
	},
	{
		Name:    "Día del Trabajador",
		Regions: []string{"cr"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Día de la Anexión de Guanacaste",
		Regions: []string{"cr"},
		Month:   7,
		Mday:    25,
		Wday:    -1,
	},
	{
		Name:    "Día de la Virgen de los Angeles",
		Regions: []string{"cr"},
		Month:   8,
		Mday:    2,
		Wday:    -1,
	},
	{
		Name:    "Día de la Madre",
		Regions: []string{"cr"},
		Month:   8,
		Mday:    15,
		Wday:    -1,
	},
	{
		Name:    "Día de la Independencia",
		Regions: []string{"cr"},
		Month:   9,
		Mday:    15,
		Wday:    -1,
	},
	{
		Name:    "Día de las Culturas",
		Regions: []string{"cr"},
		Month:   10,
		Mday:    12,
		Wday:    -1,
	},
	{
		Name:    "Navidad",
		Regions: []string{"cr"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
}

var crRegionNames = map[string]string{
	"cr": "Costa Rica",
}

func init() {
	engine.RegisterCountry("cr", crRules)
	engine.RegisterRegionNames("cr", crRegionNames)
}
