// Code generated by gen-holidays from definitions/cz.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("cz", func() {
	DescribeTable("000_DenObnovySamostatnéhoČeskéhoStátu", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Den obnovy samostatného českého státu")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den obnovy samostatného českého státu", hols))
	},
		Entry("2010-01-01", "2010-01-01"),
	)

	DescribeTable("001_VelkýPátek", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Velký pátek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Velký pátek", hols))
	},
		Entry("2016-03-25", "2016-03-25"),
	)

	DescribeTable("002_VelikonočníPondělí", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Velikonoční pondělí")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Velikonoční pondělí", hols))
	},
		Entry("2010-04-05", "2010-04-05"),
	)

	DescribeTable("003_SvátekPráce", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Svátek práce")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Svátek práce", hols))
	},
		Entry("2010-05-01", "2010-05-01"),
	)

	DescribeTable("004_DenVítězství", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Den vítězství")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den vítězství", hols))
	},
		Entry("2010-05-08", "2010-05-08"),
	)

	DescribeTable("005_DenSlovanskýchVěrozvěstůCyrilaAMetoděje", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Den slovanských věrozvěstů Cyrila a Metoděje")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den slovanských věrozvěstů Cyrila a Metoděje", hols))
	},
		Entry("2010-07-05", "2010-07-05"),
	)

	DescribeTable("006_DenUpáleníMistraJanaHusa", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Den upálení mistra Jana Husa")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den upálení mistra Jana Husa", hols))
	},
		Entry("2010-07-06", "2010-07-06"),
	)

	DescribeTable("007_DenČeskéStátnosti", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Den české státnosti")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den české státnosti", hols))
	},
		Entry("2010-09-28", "2010-09-28"),
	)

	DescribeTable("008_DenVznikuSamostatnéhoČeskoslovenskéhoStátu", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Den vzniku samostatného československého státu")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den vzniku samostatného československého státu", hols))
	},
		Entry("2010-10-28", "2010-10-28"),
	)

	DescribeTable("009_DenBojeZaSvoboduADemokracii", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Den boje za svobodu a demokracii")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Den boje za svobodu a demokracii", hols))
	},
		Entry("2010-11-17", "2010-11-17"),
	)

	DescribeTable("010_ŠtědrýDen", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Štědrý den")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Štědrý den", hols))
	},
		Entry("2010-12-24", "2010-12-24"),
	)

	DescribeTable("011_1SvátekVánoční", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "1. svátek vánoční")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. svátek vánoční", hols))
	},
		Entry("2010-12-25", "2010-12-25"),
	)

	DescribeTable("012_2SvátekVánoční", func(s string) {
		opts := holidays.Options{Regions: []string{"cz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2. svátek vánoční")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. svátek vánoční", hols))
	},
		Entry("2010-12-26", "2010-12-26"),
	)

})
