// Code generated by gen-holidays from definitions/dk.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var dkRules = []definition.HolidayRule{
	{
		Name:             "Fastelavn",
		Regions:          []string{"dk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -49,
		Type:             definition.Informal,
	},
	{
		Name:             "Palmesøndag",
		Regions:          []string{"dk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -7,
		Type:             definition.Informal,
	},
	{
		Name:             "Skærtorsdag",
		Regions:          []string{"dk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -3,
	},
	{
		Name:             "Langfredag",
		Regions:          []string{"dk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:         "Påskedag",
		Regions:      []string{"dk"},
		Month:        0,
		Wday:         -1,
		Function:     "easter",
		FunctionArgs: []string{"year"},
	},
	{
		Name:             "2. påskedag",
		Regions:          []string{"dk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:             "Store Bededag",
		Regions:          []string{"dk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 26,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeUntil, Years: []int{2023}},
		},
	},
	{
		Name:             "Kristi Himmelfartsdag",
		Regions:          []string{"dk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 39,
	},
	{
		Name:             "Pinsedag",
		Regions:          []string{"dk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 49,
	},
	{
		Name:             "2. Pinsedag",
		Regions:          []string{"dk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 50,
	},
	{
		Name:    "Nytårsdag",
		Regions: []string{"dk"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "1. april",
		Regions: []string{"dk"},
		Month:   4,
		Mday:    1,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Danmarks besættelse",
		Regions: []string{"dk"},
		Month:   4,
		Mday:    9,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Dronningens fødselsdag",
		Regions: []string{"dk"},
		Month:   4,
		Mday:    16,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Arbejdernes kampdag",
		Regions: []string{"dk"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Danmarks befrielse",
		Regions: []string{"dk"},
		Month:   5,
		Mday:    5,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Grundlovsdag",
		Regions: []string{"dk"},
		Month:   6,
		Mday:    5,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Valdemarsdag og Genforeningsdag",
		Regions: []string{"dk"},
		Month:   6,
		Mday:    15,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Sankt Hans aften",
		Regions: []string{"dk"},
		Month:   6,
		Mday:    23,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Mortensaften",
		Regions: []string{"dk"},
		Month:   11,
		Mday:    10,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Sankt Lucia",
		Regions: []string{"dk"},
		Month:   12,
		Mday:    13,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Juleaftensdag",
		Regions: []string{"dk"},
		Month:   12,
		Mday:    24,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "1. juledag",
		Regions: []string{"dk"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
	{
		Name:    "2. juledag",
		Regions: []string{"dk"},
		Month:   12,
		Mday:    26,
		Wday:    -1,
	},
}

var dkRegionNames = map[string]string{
	"dk": "Denmark",
}

func init() {
	engine.RegisterCountry("dk", dkRules)
	engine.RegisterRegionNames("dk", dkRegionNames)
}
