// Code generated by gen-holidays from definitions/ecbtarget.yaml@v9.0.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("ecbtarget", func() {
	DescribeTable("000_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ecbtarget"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2013-01-01", "2013-01-01"),
	)

	DescribeTable("001_LabourDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ecbtarget"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Labour Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labour Day", hols))
	},
		Entry("2013-05-01", "2013-05-01"),
	)

	DescribeTable("002_GoodFriday", func(s string) {
		opts := holidays.Options{Regions: []string{"ecbtarget"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Good Friday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols))
	},
		Entry("2013-03-29", "2013-03-29"),
	)

	DescribeTable("003_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"ecbtarget"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2013-04-01", "2013-04-01"),
	)

	DescribeTable("004_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ecbtarget"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2013-12-25", "2013-12-25"),
	)

	DescribeTable("005_ChristmasHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"ecbtarget"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Holiday", hols))
	},
		Entry("2013-12-26", "2013-12-26"),
	)

	DescribeTable("006_GoodFriday", func(s string) {
		opts := holidays.Options{Regions: []string{"ecbtarget"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Good Friday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols))
	},
		Entry("2013-03-29", "2013-03-29"),
	)

	DescribeTable("007_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"ecbtarget"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2013-04-01", "2013-04-01"),
	)

})
