// Code generated by gen-holidays from definitions/ecbtarget.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var ecbtargetRules = []definition.HolidayRule{
	{
		Name:             "Good Friday",
		Regions:          []string{"ecbtarget"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:             "Easter Monday",
		Regions:          []string{"ecbtarget"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:    "New Year's Day",
		Regions: []string{"ecbtarget"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Labour Day",
		Regions: []string{"ecbtarget"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Christmas Day",
		Regions: []string{"ecbtarget"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
	{
		Name:    "Christmas Holiday",
		Regions: []string{"ecbtarget"},
		Month:   12,
		Mday:    26,
		Wday:    -1,
	},
}

var ecbtargetRegionNames = map[string]string{
	"ecbtarget": "ECB TARGET (European Central Bank)",
}

func init() {
	engine.RegisterCountry("ecbtarget", ecbtargetRules)
	engine.RegisterRegionNames("ecbtarget", ecbtargetRegionNames)
}
