// Code generated by gen-holidays from definitions/ee.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var eeRules = []definition.HolidayRule{
	{
		Name:             "suur reede",
		Regions:          []string{"ee"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:         "ülestõusmispühade 1. püha",
		Regions:      []string{"ee"},
		Month:        0,
		Wday:         -1,
		Function:     "easter",
		FunctionArgs: []string{"year"},
	},
	{
		Name:             "nelipühade 1. püha",
		Regions:          []string{"ee"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 49,
	},
	{
		Name:    "uusaasta",
		Regions: []string{"ee"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "iseseisvuspäev",
		Regions: []string{"ee"},
		Month:   2,
		Mday:    24,
		Wday:    -1,
	},
	{
		Name:    "kevadpüha",
		Regions: []string{"ee"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "võidupüha ja jaanilaupäev",
		Regions: []string{"ee"},
		Month:   6,
		Mday:    23,
		Wday:    -1,
	},
	{
		Name:    "jaanipäev",
		Regions: []string{"ee"},
		Month:   6,
		Mday:    24,
		Wday:    -1,
	},
	{
		Name:    "taasiseseisvumispäev",
		Regions: []string{"ee"},
		Month:   8,
		Mday:    20,
		Wday:    -1,
	},
	{
		Name:    "jõululaupäev",
		Regions: []string{"ee"},
		Month:   12,
		Mday:    24,
		Wday:    -1,
	},
	{
		Name:    "esimene jõulupüha",
		Regions: []string{"ee"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
	{
		Name:    "teine jõulupüha",
		Regions: []string{"ee"},
		Month:   12,
		Mday:    26,
		Wday:    -1,
	},
}

var eeRegionNames = map[string]string{
	"ee": "Estonia",
}

func init() {
	engine.RegisterCountry("ee", eeRules)
	engine.RegisterRegionNames("ee", eeRegionNames)
}
