// Code generated by gen-holidays from definitions/ee.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("ee", func() {
	DescribeTable("000_Uusaasta", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "uusaasta")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "uusaasta", hols))
	},
		Entry("2017-01-01", "2017-01-01"),
	)

	DescribeTable("001_Iseseisvuspäev", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "iseseisvuspäev")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "iseseisvuspäev", hols))
	},
		Entry("2017-2-24", "2017-2-24"),
	)

	DescribeTable("002_Kevadpüha", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "kevadpüha")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "kevadpüha", hols))
	},
		Entry("2017-5-1", "2017-5-1"),
	)

	DescribeTable("003_VõidupühaJaJaanilaupäev", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "võidupüha ja jaanilaupäev")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "võidupüha ja jaanilaupäev", hols))
	},
		Entry("2017-6-23", "2017-6-23"),
	)

	DescribeTable("004_Jaanipäev", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "jaanipäev")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "jaanipäev", hols))
	},
		Entry("2017-6-24", "2017-6-24"),
	)

	DescribeTable("005_Taasiseseisvumispäev", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "taasiseseisvumispäev")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "taasiseseisvumispäev", hols))
	},
		Entry("2017-8-20", "2017-8-20"),
	)

	DescribeTable("006_Jõululaupäev", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "jõululaupäev")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "jõululaupäev", hols))
	},
		Entry("2017-12-24", "2017-12-24"),
	)

	DescribeTable("007_EsimeneJõulupüha", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "esimene jõulupüha")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "esimene jõulupüha", hols))
	},
		Entry("2017-12-25", "2017-12-25"),
	)

	DescribeTable("008_TeineJõulupüha", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "teine jõulupüha")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "teine jõulupüha", hols))
	},
		Entry("2017-12-26", "2017-12-26"),
	)

	DescribeTable("009_SuurReede", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "suur reede")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "suur reede", hols))
	},
		Entry("2017-4-14", "2017-4-14"),
		Entry("2018-3-30", "2018-3-30"),
		Entry("2019-4-19", "2019-4-19"),
	)

	DescribeTable("010_Ülestõusmispühade1Püha", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "ülestõusmispühade 1. püha")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "ülestõusmispühade 1. püha", hols))
	},
		Entry("2017-4-16", "2017-4-16"),
		Entry("2018-4-1", "2018-4-1"),
		Entry("2019-4-21", "2019-4-21"),
	)

	DescribeTable("011_Nelipühade1Püha", func(s string) {
		opts := holidays.Options{Regions: []string{"ee"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "nelipühade 1. püha")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "nelipühade 1. püha", hols))
	},
		Entry("2017-6-4", "2017-6-4"),
		Entry("2018-5-20", "2018-5-20"),
		Entry("2019-6-9", "2019-6-9"),
	)

})
