// Code generated by gen-holidays from definitions/federalreservebanks.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var federalreservebanksRules = []definition.HolidayRule{
	{
		Name:     "New Year's Day",
		Regions:  []string{"federalreservebanks"},
		Month:    1,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:    "Birthday of Martin Luther King, Jr",
		Regions: []string{"federalreservebanks"},
		Month:   1,
		Wday:    1,
		Week:    3,
	},
	{
		Name:    "Washington's Birthday",
		Regions: []string{"federalreservebanks"},
		Month:   2,
		Wday:    1,
		Week:    3,
	},
	{
		Name:    "Memorial Day",
		Regions: []string{"federalreservebanks"},
		Month:   5,
		Wday:    1,
		Week:    -1,
	},
	{
		Name:     "Juneteenth National Independence Day",
		Regions:  []string{"federalreservebanks"},
		Month:    6,
		Mday:     19,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2021}},
		},
	},
	{
		Name:     "Independence Day",
		Regions:  []string{"federalreservebanks"},
		Month:    7,
		Mday:     4,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:    "Labor Day",
		Regions: []string{"federalreservebanks"},
		Month:   9,
		Wday:    1,
		Week:    1,
	},
	{
		Name:    "Columbus Day",
		Regions: []string{"federalreservebanks"},
		Month:   10,
		Wday:    1,
		Week:    2,
	},
	{
		Name:     "Veterans Day",
		Regions:  []string{"federalreservebanks"},
		Month:    11,
		Mday:     11,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:    "Thanksgiving Day",
		Regions: []string{"federalreservebanks"},
		Month:   11,
		Wday:    4,
		Week:    4,
	},
	{
		Name:     "Christmas Day",
		Regions:  []string{"federalreservebanks"},
		Month:    12,
		Mday:     25,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
}

var federalreservebanksRegionNames = map[string]string{
	"federalreservebanks": "Federal Reserve Banks",
}

func init() {
	engine.RegisterCountry("federalreservebanks", federalreservebanksRules)
	engine.RegisterRegionNames("federalreservebanks", federalreservebanksRegionNames)
}
