// Code generated by gen-holidays from definitions/fi.yaml@v9.0.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("fi", func() {
	DescribeTable("000_Uudenvuodenpäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Uudenvuodenpäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Uudenvuodenpäivä", hols))
	},
		Entry("2008-01-01", "2008-01-01"),
	)

	DescribeTable("001_Loppiainen", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Loppiainen")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Loppiainen", hols))
	},
		Entry("2008-01-06", "2008-01-06"),
	)

	DescribeTable("002_Pitkäperjantai", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Pitkäperjantai")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pitkäperjantai", hols))
	},
		Entry("2008-03-21", "2008-03-21"),
	)

	DescribeTable("003_Pääsiäispäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Pääsiäispäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pääsiäispäivä", hols))
	},
		Entry("2008-03-23", "2008-03-23"),
	)

	DescribeTable("004_2Pääsiäispäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2. Pääsiäispäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. Pääsiäispäivä", hols))
	},
		Entry("2008-03-24", "2008-03-24"),
	)

	DescribeTable("005_Helatorstai", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Helatorstai")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Helatorstai", hols))
	},
		Entry("2008-05-01", "2008-05-01"),
	)

	DescribeTable("006_Helluntaipäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Helluntaipäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Helluntaipäivä", hols))
	},
		Entry("2008-05-11", "2008-05-11"),
	)

	DescribeTable("007_Juhannusaatto", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Juhannusaatto")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannusaatto", hols))
	},
		Entry("2009-06-19", "2009-06-19"),
	)

	DescribeTable("008_Juhannusaatto", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Juhannusaatto")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannusaatto", hols))
	},
		Entry("2010-06-25", "2010-06-25"),
	)

	DescribeTable("009_Juhannusaatto", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Juhannusaatto")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannusaatto", hols))
	},
		Entry("2011-06-24", "2011-06-24"),
	)

	DescribeTable("010_Juhannusaatto", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Juhannusaatto")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannusaatto", hols))
	},
		Entry("2012-06-22", "2012-06-22"),
	)

	DescribeTable("011_Juhannusaatto", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Juhannusaatto")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannusaatto", hols))
	},
		Entry("2013-06-21", "2013-06-21"),
	)

	DescribeTable("012_Juhannuspäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Juhannuspäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannuspäivä", hols))
	},
		Entry("2005-06-25", "2005-06-25"),
	)

	DescribeTable("013_Juhannuspäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Juhannuspäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannuspäivä", hols))
	},
		Entry("2006-06-24", "2006-06-24"),
	)

	DescribeTable("014_Juhannuspäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Juhannuspäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannuspäivä", hols))
	},
		Entry("2007-06-23", "2007-06-23"),
	)

	DescribeTable("015_Juhannuspäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Juhannuspäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juhannuspäivä", hols))
	},
		Entry("2008-06-21", "2008-06-21"),
	)

	DescribeTable("016_Pyhäinpäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Pyhäinpäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pyhäinpäivä", hols))
	},
		Entry("2005-11-05", "2005-11-05"),
	)

	DescribeTable("017_Pyhäinpäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Pyhäinpäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pyhäinpäivä", hols))
	},
		Entry("2006-11-04", "2006-11-04"),
	)

	DescribeTable("018_Pyhäinpäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Pyhäinpäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pyhäinpäivä", hols))
	},
		Entry("2007-11-03", "2007-11-03"),
	)

	DescribeTable("019_Pyhäinpäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Pyhäinpäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pyhäinpäivä", hols))
	},
		Entry("2008-11-01", "2008-11-01"),
	)

	DescribeTable("020_Itsenäisyyspäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Itsenäisyyspäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Itsenäisyyspäivä", hols))
	},
		Entry("2008-12-06", "2008-12-06"),
	)

	DescribeTable("021_Jouluaatto", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Jouluaatto")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jouluaatto", hols))
	},
		Entry("2008-12-24", "2008-12-24"),
	)

	DescribeTable("022_Joulupäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Joulupäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Joulupäivä", hols))
	},
		Entry("2008-12-25", "2008-12-25"),
	)

	DescribeTable("023_Tapaninpäivä", func(s string) {
		opts := holidays.Options{Regions: []string{"fi"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Tapaninpäivä")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tapaninpäivä", hols))
	},
		Entry("2008-12-26", "2008-12-26"),
	)

})
