// Code generated by gen-holidays from definitions/fr.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var frRules = []definition.HolidayRule{
	{
		Name:             "Vendredi saint",
		Regions:          []string{"fr_a", "fr_m"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:         "Pâques",
		Regions:      []string{"fr"},
		Month:        0,
		Wday:         -1,
		Function:     "easter",
		FunctionArgs: []string{"year"},
		Type:         definition.Informal,
	},
	{
		Name:             "Lundi de Pâques",
		Regions:          []string{"fr"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:             "Ascension",
		Regions:          []string{"fr"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 39,
	},
	{
		Name:             "Pentecôte",
		Regions:          []string{"fr"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 49,
		Type:             definition.Informal,
	},
	{
		Name:             "Lundi de Pentecôte",
		Regions:          []string{"fr"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 50,
	},
	{
		Name:    "Jour de l'an",
		Regions: []string{"fr"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Fête du travail",
		Regions: []string{"fr"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Victoire 1945",
		Regions: []string{"fr"},
		Month:   5,
		Mday:    8,
		Wday:    -1,
	},
	{
		Name:    "Fête nationale",
		Regions: []string{"fr"},
		Month:   7,
		Mday:    14,
		Wday:    -1,
	},
	{
		Name:    "Assomption",
		Regions: []string{"fr"},
		Month:   8,
		Mday:    15,
		Wday:    -1,
	},
	{
		Name:    "Toussaint",
		Regions: []string{"fr"},
		Month:   11,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Armistice 1918",
		Regions: []string{"fr"},
		Month:   11,
		Mday:    11,
		Wday:    -1,
	},
	{
		Name:    "Noël",
		Regions: []string{"fr"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
	{
		Name:    "Saint-Étienne",
		Regions: []string{"fr_a", "fr_m"},
		Month:   12,
		Mday:    26,
		Wday:    -1,
	},
}

var frRegionNames = map[string]string{
	"fr":   "France",
	"fr_a": "Alsace",
	"fr_m": "Moselle",
}

func init() {
	engine.RegisterCountry("fr", frRules)
	engine.RegisterRegionNames("fr", frRegionNames)
}
