// Code generated by gen-holidays from definitions/gb.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var gbRules = []definition.HolidayRule{
	{
		Name:             "Mothering Sunday",
		Regions:          []string{"gb"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -21,
		Type:             definition.Informal,
	},
	{
		Name:             "Good Friday",
		Regions:          []string{"gb"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:         "Easter Sunday",
		Regions:      []string{"gb"},
		Month:        0,
		Wday:         -1,
		Function:     "easter",
		FunctionArgs: []string{"year"},
	},
	{
		Name:             "Easter Monday",
		Regions:          []string{"gb_eng", "gb_wls", "gb_eaw", "gb_nir", "gb_con", "je", "gb_jsy", "gg", "gb_gsy"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:     "New Year's Day",
		Regions:  []string{"gb"},
		Month:    1,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:     "2nd January",
		Regions:  []string{"gb_sct"},
		Month:    1,
		Mday:     2,
		Wday:     -1,
		Observed: "to_weekday_if_boxing_weekend",
	},
	{
		Name:    "St. Piran's Day",
		Regions: []string{"gb_con"},
		Month:   3,
		Mday:    5,
		Wday:    -1,
	},
	{
		Name:     "St. Patrick's Day",
		Regions:  []string{"gb_nir"},
		Month:    3,
		Mday:     17,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:    "May Day",
		Regions: []string{"gb"},
		Month:   5,
		Wday:    1,
		Week:    1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeUntil, Years: []int{2019}},
		},
	},
	{
		Name:    "May Day",
		Regions: []string{"gb"},
		Month:   5,
		Mday:    8,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2020}},
		},
	},
	{
		Name:    "Bank Holiday for the Coronation of King Charles III",
		Regions: []string{"gb"},
		Month:   5,
		Mday:    8,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "May Day",
		Regions: []string{"gb"},
		Month:   5,
		Wday:    1,
		Week:    1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2021}},
		},
	},
	{
		Name:    "Liberation Day",
		Regions: []string{"je", "gb_jsy", "gg", "gb_gsy"},
		Month:   5,
		Mday:    9,
		Wday:    -1,
	},
	{
		Name:    "Bank Holiday",
		Regions: []string{"gb"},
		Month:   5,
		Wday:    1,
		Week:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeUntil, Years: []int{2021}},
		},
	},
	{
		Name:    "Bank Holiday",
		Regions: []string{"gb"},
		Month:   5,
		Wday:    1,
		Week:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2023}},
		},
	},
	{
		Name:    "Bank Holiday for the Coronation of King Charles III",
		Regions: []string{"gb"},
		Month:   5,
		Mday:    8,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "Bank Holiday",
		Regions: []string{"gb"},
		Month:   6,
		Mday:    2,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "Platinum Jubilee",
		Regions: []string{"gb"},
		Month:   6,
		Mday:    3,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "World Cup Bank Holiday",
		Regions: []string{"gb_sct"},
		Month:   6,
		Mday:    15,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2026}},
		},
	},
	{
		Name:    "Tynwald Day",
		Regions: []string{"im", "gb_iom"},
		Month:   7,
		Mday:    5,
		Wday:    -1,
	},
	{
		Name:     "Battle of the Boyne",
		Regions:  []string{"gb_nir"},
		Month:    7,
		Mday:     12,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:    "Bank Holiday",
		Regions: []string{"gb_sct"},
		Month:   8,
		Wday:    1,
		Week:    1,
	},
	{
		Name:    "Bank Holiday",
		Regions: []string{"gb_eng", "gb_wls", "gb_eaw", "gb_nir", "gb_con", "je", "gb_jsy", "gg", "gb_gsy"},
		Month:   8,
		Wday:    1,
		Week:    -1,
	},
	{
		Name:    "Bank Holiday for the State Funeral of Queen Elizabeth II",
		Regions: []string{"gb"},
		Month:   9,
		Mday:    19,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "Guy Fawkes Day",
		Regions: []string{"gb"},
		Month:   11,
		Mday:    5,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:     "St. Andrew's Day",
		Regions:  []string{"gb_sct"},
		Month:    11,
		Mday:     30,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
		Type:     definition.Informal,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeUntil, Years: []int{2006}},
		},
	},
	{
		Name:     "St. Andrew's Day",
		Regions:  []string{"gb_sct"},
		Month:    11,
		Mday:     30,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2007}},
		},
	},
	{
		Name:     "Christmas Day",
		Regions:  []string{"gb"},
		Month:    12,
		Mday:     25,
		Wday:     -1,
		Observed: "to_tuesday_if_sunday_or_monday_if_saturday",
	},
	{
		Name:     "Boxing Day",
		Regions:  []string{"gb"},
		Month:    12,
		Mday:     26,
		Wday:     -1,
		Observed: "to_tuesday_if_sunday_or_monday_if_saturday",
	},
}

var gbRegionNames = map[string]string{
	"gb":     "United Kingdom",
	"gb_con": "Cornwall",
	"gb_eaw": "England and Wales",
	"gb_eng": "England",
	"gb_gsy": "Guernsey",
	"gb_iom": "Isle of Man",
	"gb_jsy": "Jersey",
	"gb_nir": "Northern Ireland",
	"gb_sct": "Scotland",
	"gb_wls": "Wales",
	"gg":     "Guernsey",
	"im":     "Isle of Man",
	"je":     "Jersey",
}

func init() {
	engine.RegisterCountry("gb", gbRules)
	engine.RegisterRegionNames("gb", gbRegionNames)
}
