// Code generated by gen-holidays from definitions/gb.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("gb", func() {
	DescribeTable("000_MotheringSunday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Mothering Sunday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Mothering Sunday", hols))
	},
		Entry("2022-03-27", "2022-03-27"),
	)

	DescribeTable("001_MotheringSunday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Mothering Sunday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Mothering Sunday", hols))
	},
		Entry("2021-03-14", "2021-03-14"),
	)

	DescribeTable("002_GoodFriday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Good Friday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols))
	},
		Entry("2008-03-21", "2008-03-21"),
	)

	DescribeTable("003_EasterSunday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Sunday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Sunday", hols))
	},
		Entry("2008-03-23", "2008-03-23"),
	)

	DescribeTable("004_MayDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "May Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "May Day", hols))
	},
		Entry("2008-05-05", "2008-05-05"),
	)

	DescribeTable("005_BankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday", hols))
	},
		Entry("2008-05-26", "2008-05-26"),
	)

	DescribeTable("006_GuyFawkesDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Guy Fawkes Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Guy Fawkes Day", hols))
	},
		Entry("2008-11-05", "2008-11-05"),
	)

	DescribeTable("007_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2008-12-25", "2008-12-25"),
	)

	DescribeTable("008_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2008-12-26", "2008-12-26"),
	)

	DescribeTable("009_StPatrickSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Patrick's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Patrick's Day", hols))
	},
		Entry("2008-03-17", "2008-03-17"),
	)

	DescribeTable("010_StPatrickSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Patrick's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Patrick's Day", hols))
	},
		Entry("2018-03-17", "2018-03-17"),
	)

	DescribeTable("011_StPatrickSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Patrick's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Patrick's Day", hols))
	},
		Entry("2018-03-19", "2018-03-19"),
	)

	DescribeTable("012_StPatrickSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Patrick's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Patrick's Day", hols))
	},
		Entry("2019-03-17", "2019-03-17"),
	)

	DescribeTable("013_StPatrickSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Patrick's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Patrick's Day", hols))
	},
		Entry("2019-03-18", "2019-03-18"),
	)

	DescribeTable("014_BattleOfTheBoyne", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Battle of the Boyne")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Battle of the Boyne", hols))
	},
		Entry("2020-07-12", "2020-07-12"),
	)

	DescribeTable("015_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2020-07-12", "2020-07-12"),
	)

	DescribeTable("016_BattleOfTheBoyne", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Battle of the Boyne")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Battle of the Boyne", hols))
	},
		Entry("2020-07-13", "2020-07-13"),
	)

	DescribeTable("017_BattleOfTheBoyne", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Battle of the Boyne")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Battle of the Boyne", hols))
	},
		Entry("2008-07-12", "2008-07-12"),
	)

	DescribeTable("018_BattleOfTheBoyne", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Battle of the Boyne")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Battle of the Boyne", hols))
	},
		Entry("2008-07-14", "2008-07-14"),
	)

	DescribeTable("019_BattleOfTheBoyne", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Battle of the Boyne")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Battle of the Boyne", hols))
	},
		Entry("2021-07-12", "2021-07-12"),
	)

	DescribeTable("020_BattleOfTheBoyne", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Battle of the Boyne")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Battle of the Boyne", hols))
	},
		Entry("2021-07-12", "2021-07-12"),
	)

	DescribeTable("021_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2021-07-13", "2021-07-13"),
	)

	DescribeTable("022_StAndrewSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Andrew's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Andrew's Day", hols))
	},
		Entry("2006-11-30", "2006-11-30"),
	)

	DescribeTable("023_StAndrewSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Informal: true, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Andrew's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Andrew's Day", hols))
	},
		Entry("2006-11-30", "2006-11-30"),
	)

	DescribeTable("024_StAndrewSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Informal: true, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Andrew's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Andrew's Day", hols))
	},
		Entry("2002-12-02", "2002-12-02"),
	)

	DescribeTable("025_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2004-11-30", "2004-11-30"),
	)

	DescribeTable("026_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2005-11-30", "2005-11-30"),
	)

	DescribeTable("027_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2006-11-30", "2006-11-30"),
	)

	DescribeTable("028_StAndrewSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Andrew's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Andrew's Day", hols))
	},
		Entry("2007-11-30", "2007-11-30"),
	)

	DescribeTable("029_StAndrewSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Andrew's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Andrew's Day", hols))
	},
		Entry("2007-11-30", "2007-11-30"),
	)

	DescribeTable("030_StAndrewSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Informal: true, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Andrew's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Andrew's Day", hols))
	},
		Entry("2007-11-30", "2007-11-30"),
	)

	DescribeTable("031_StAndrewSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Andrew's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Andrew's Day", hols))
	},
		Entry("2016-11-30", "2016-11-30"),
	)

	DescribeTable("032_StAndrewSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Andrew's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Andrew's Day", hols))
	},
		Entry("2019-11-30", "2019-11-30"),
	)

	DescribeTable("033_StAndrewSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Andrew's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Andrew's Day", hols))
	},
		Entry("2019-11-30", "2019-11-30"),
	)

	DescribeTable("034_StAndrewSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Andrew's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Andrew's Day", hols))
	},
		Entry("2019-12-2", "2019-12-2"),
	)

	DescribeTable("035_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2008-12-25", "2008-12-25"),
	)

	DescribeTable("036_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2009-12-25", "2009-12-25"),
	)

	DescribeTable("037_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2010-12-27", "2010-12-27"),
	)

	DescribeTable("038_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2008-12-26", "2008-12-26"),
	)

	DescribeTable("039_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2009-12-28", "2009-12-28"),
	)

	DescribeTable("040_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2010-12-28", "2010-12-28"),
	)

	DescribeTable("041_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2011-12-27", "2011-12-27"),
	)

	DescribeTable("042_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2011-12-26", "2011-12-26"),
	)

	DescribeTable("043_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2022-12-26", "2022-12-26"),
	)

	DescribeTable("044_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2022-12-27", "2022-12-27"),
	)

	DescribeTable("045_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2010-01-01", "2010-01-01"),
	)

	DescribeTable("046_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2011-01-03", "2011-01-03"),
	)

	DescribeTable("047_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2012-01-02", "2012-01-02"),
	)

	DescribeTable("048_2ndJanuary", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2nd January")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2nd January", hols))
	},
		Entry("2010-01-04", "2010-01-04"),
	)

	DescribeTable("049_2ndJanuary", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2nd January")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2nd January", hols))
	},
		Entry("2011-01-04", "2011-01-04"),
	)

	DescribeTable("050_2ndJanuary", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2nd January")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2nd January", hols))
	},
		Entry("2012-01-03", "2012-01-03"),
	)

	DescribeTable("051_2ndJanuary", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2nd January")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2nd January", hols))
	},
		Entry("2013-01-02", "2013-01-02"),
	)

	DescribeTable("052_2ndJanuary", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2nd January")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2nd January", hols))
	},
		Entry("2014-01-02", "2014-01-02"),
	)

	DescribeTable("053_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_wls"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2008-03-24", "2008-03-24"),
	)

	DescribeTable("054_BankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_wls"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday", hols))
	},
		Entry("2008-08-25", "2008-08-25"),
	)

	DescribeTable("055_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2008-03-24", "2008-03-24"),
	)

	DescribeTable("056_BankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday", hols))
	},
		Entry("2008-08-25", "2008-08-25"),
	)

	DescribeTable("057_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2008-03-24", "2008-03-24"),
	)

	DescribeTable("058_BankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday", hols))
	},
		Entry("2008-08-25", "2008-08-25"),
	)

	DescribeTable("059_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eaw"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2008-03-24", "2008-03-24"),
	)

	DescribeTable("060_BankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eaw"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday", hols))
	},
		Entry("2008-08-25", "2008-08-25"),
	)

	DescribeTable("061_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2008-03-24", "2008-03-24"),
	)

	DescribeTable("062_BankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday", hols))
	},
		Entry("2008-08-25", "2008-08-25"),
	)

	DescribeTable("063_LiberationDay", func(s string) {
		opts := holidays.Options{Regions: []string{"je"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Liberation Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Liberation Day", hols))
	},
		Entry("2018-05-09", "2018-05-09"),
	)

	DescribeTable("064_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"je"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2018-04-02", "2018-04-02"),
	)

	DescribeTable("065_BankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"je"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday", hols))
	},
		Entry("2018-08-27", "2018-08-27"),
	)

	DescribeTable("066_BankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday", hols))
	},
		Entry("2022-06-02", "2022-06-02"),
	)

	DescribeTable("067_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2022-05-30", "2022-05-30"),
	)

	DescribeTable("068_PlatinumJubilee", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Platinum Jubilee")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Platinum Jubilee", hols))
	},
		Entry("2022-06-03", "2022-06-03"),
	)

	DescribeTable("069_BankHolidayForTheStateFuneralOfQueenElizabethII", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday for the State Funeral of Queen Elizabeth II")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday for the State Funeral of Queen Elizabeth II", hols))
	},
		Entry("2022-09-19", "2022-09-19"),
	)

	DescribeTable("070_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2023-09-19", "2023-09-19"),
	)

	DescribeTable("071_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2021-09-19", "2021-09-19"),
	)

	DescribeTable("072_BankHolidayForTheCoronationOfKingCharlesIII", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday for the Coronation of King Charles III")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday for the Coronation of King Charles III", hols))
	},
		Entry("2023-05-08", "2023-05-08"),
	)

	DescribeTable("073_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_con"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2016-03-28", "2016-03-28"),
	)

	DescribeTable("074_BankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_con"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday", hols))
	},
		Entry("2016-08-29", "2016-08-29"),
	)

	DescribeTable("075_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2024-05-08", "2024-05-08"),
	)

	DescribeTable("076_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2022-05-08", "2022-05-08"),
	)

	DescribeTable("077_BankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday", hols))
	},
		Entry("2023-05-29", "2023-05-29"),
	)

	DescribeTable("078_BankHolidayForTheCoronationOfKingCharlesIII", func(s string) {
		opts := holidays.Options{Regions: []string{"gb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bank Holiday for the Coronation of King Charles III")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bank Holiday for the Coronation of King Charles III", hols))
	},
		Entry("2023-05-08", "2023-05-08"),
	)

	DescribeTable("079_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2021-01-01", "2021-01-01"),
	)

	DescribeTable("080_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2021-01-01", "2021-01-01"),
	)

	DescribeTable("081_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2021-01-01", "2021-01-01"),
	)

	DescribeTable("082_2ndJanuary", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2nd January")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2nd January", hols))
	},
		Entry("2021-01-04", "2021-01-04"),
	)

	DescribeTable("083_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2021-12-27", "2021-12-27"),
	)

	DescribeTable("084_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2021-12-27", "2021-12-27"),
	)

	DescribeTable("085_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2021-12-27", "2021-12-27"),
	)

	DescribeTable("086_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2021-12-28", "2021-12-28"),
	)

	DescribeTable("087_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2021-12-28", "2021-12-28"),
	)

	DescribeTable("088_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2021-12-28", "2021-12-28"),
	)

	DescribeTable("089_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2023-01-02", "2023-01-02"),
	)

	DescribeTable("090_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2023-01-02", "2023-01-02"),
	)

	DescribeTable("091_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2023-01-02", "2023-01-02"),
	)

	DescribeTable("092_2ndJanuary", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2nd January")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2nd January", hols))
	},
		Entry("2023-01-03", "2023-01-03"),
	)

	DescribeTable("093_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2023-12-25", "2023-12-25"),
	)

	DescribeTable("094_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2023-12-25", "2023-12-25"),
	)

	DescribeTable("095_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2023-12-25", "2023-12-25"),
	)

	DescribeTable("096_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2023-12-26", "2023-12-26"),
	)

	DescribeTable("097_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2023-12-26", "2023-12-26"),
	)

	DescribeTable("098_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2023-12-26", "2023-12-26"),
	)

	DescribeTable("099_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2027-01-01", "2027-01-01"),
	)

	DescribeTable("100_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2027-01-01", "2027-01-01"),
	)

	DescribeTable("101_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2027-01-01", "2027-01-01"),
	)

	DescribeTable("102_2ndJanuary", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2nd January")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2nd January", hols))
	},
		Entry("2027-01-04", "2027-01-04"),
	)

	DescribeTable("103_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2027-12-27", "2027-12-27"),
	)

	DescribeTable("104_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2027-12-27", "2027-12-27"),
	)

	DescribeTable("105_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2027-12-27", "2027-12-27"),
	)

	DescribeTable("106_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2027-12-28", "2027-12-28"),
	)

	DescribeTable("107_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2027-12-28", "2027-12-28"),
	)

	DescribeTable("108_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2027-12-28", "2027-12-28"),
	)

	DescribeTable("109_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2028-01-03", "2028-01-03"),
	)

	DescribeTable("110_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2028-01-03", "2028-01-03"),
	)

	DescribeTable("111_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2028-01-03", "2028-01-03"),
	)

	DescribeTable("112_2ndJanuary", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2nd January")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2nd January", hols))
	},
		Entry("2028-01-04", "2028-01-04"),
	)

	DescribeTable("113_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2028-12-25", "2028-12-25"),
	)

	DescribeTable("114_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2028-12-25", "2028-12-25"),
	)

	DescribeTable("115_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2028-12-25", "2028-12-25"),
	)

	DescribeTable("116_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2028-12-26", "2028-12-26"),
	)

	DescribeTable("117_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2028-12-26", "2028-12-26"),
	)

	DescribeTable("118_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2028-12-26", "2028-12-26"),
	)

	DescribeTable("119_WorldCupBankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "World Cup Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "World Cup Bank Holiday", hols))
	},
		Entry("2026-06-15", "2026-06-15"),
	)

	DescribeTable("120_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_eng"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2026-06-15", "2026-06-15"),
	)

	DescribeTable("121_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_nir"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2026-06-15", "2026-06-15"),
	)

	DescribeTable("122_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2025-06-15", "2025-06-15"),
	)

	DescribeTable("123_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"gb_sct"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2027-06-15", "2027-06-15"),
	)

})
