// Code generated by gen-holidays from definitions/hk.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var hkRules = []definition.HolidayRule{
	{
		Name:             "Good Friday",
		Regions:          []string{"hk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:             "The day following Good Friday",
		Regions:          []string{"hk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -1,
	},
	{
		Name:             "Easter Monday",
		Regions:          []string{"hk"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:     "New Year's Day",
		Regions:  []string{"hk"},
		Month:    1,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:         "Lunar New Year's Day",
		Regions:      []string{"hk"},
		Month:        1,
		Mday:         1,
		Wday:         -1,
		Function:     "lunar_to_solar",
		FunctionArgs: []string{"year", "month", "day", "region"},
		Observed:     "to_monday_if_sunday",
	},
	{
		Name:         "The second day of Lunar New Year",
		Regions:      []string{"hk"},
		Month:        1,
		Mday:         1,
		Wday:         -1,
		Function:     "lunar_to_solar",
		FunctionArgs: []string{"year", "month", "day", "region"},
		Observed:     "to_the_weekday_after",
	},
	{
		Name:         "The third day of Lunar New Year",
		Regions:      []string{"hk"},
		Month:        1,
		Mday:         1,
		Wday:         -1,
		Function:     "lunar_to_solar",
		FunctionArgs: []string{"year", "month", "day", "region"},
		Observed:     "to_the_second_weekday_after",
	},
	{
		Name:     "Ching Ming Festival",
		Regions:  []string{"hk"},
		Month:    4,
		Mday:     5,
		Wday:     -1,
		Observed: "to_previous_day_if_leap_year",
	},
	{
		Name:         "Buddha's Birthday",
		Regions:      []string{"hk"},
		Month:        4,
		Mday:         8,
		Wday:         -1,
		Function:     "lunar_to_solar",
		FunctionArgs: []string{"year", "month", "day", "region"},
		Observed:     "to_monday_if_sunday",
	},
	{
		Name:     "Labour Day",
		Regions:  []string{"hk"},
		Month:    5,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:         "Tuen Ng Festival",
		Regions:      []string{"hk"},
		Month:        5,
		Mday:         5,
		Wday:         -1,
		Function:     "lunar_to_solar",
		FunctionArgs: []string{"year", "month", "day", "region"},
		Observed:     "to_monday_if_sunday",
	},
	{
		Name:     "Hong Kong Special Administrative Region Establishment Day",
		Regions:  []string{"hk"},
		Month:    7,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:         "The day following the Chinese Mid-Autumn Festival",
		Regions:      []string{"hk"},
		Month:        8,
		Mday:         16,
		Wday:         -1,
		Function:     "lunar_to_solar",
		FunctionArgs: []string{"year", "month", "day", "region"},
		Observed:     "to_monday_if_sunday",
	},
	{
		Name:         "Chung Yeung Festival",
		Regions:      []string{"hk"},
		Month:        9,
		Mday:         9,
		Wday:         -1,
		Function:     "lunar_to_solar",
		FunctionArgs: []string{"year", "month", "day", "region"},
		Observed:     "to_monday_if_sunday",
	},
	{
		Name:     "National Day",
		Regions:  []string{"hk"},
		Month:    10,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:     "Christmas Day",
		Regions:  []string{"hk"},
		Month:    12,
		Mday:     25,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:     "Boxing Day",
		Regions:  []string{"hk"},
		Month:    12,
		Mday:     26,
		Wday:     -1,
		Observed: "to_weekday_if_boxing_weekend",
	},
}

var hkRegionNames = map[string]string{
	"hk": "Hong Kong",
}

func init() {
	engine.RegisterCountry("hk", hkRules)
	engine.RegisterRegionNames("hk", hkRegionNames)
}
