// Code generated by gen-holidays from definitions/hu.yaml@v9.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var huRules = []definition.HolidayRule{
	{
		Name:             "Nagypéntek",
		Regions:          []string{"hu"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2017}},
		},
	},
	{
		Name:             "Húsvéthétfő",
		Regions:          []string{"hu"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:             "Pünkösdhétfő",
		Regions:          []string{"hu"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 50,
	},
	{
		Name:    "Újév",
		Regions: []string{"hu"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "1848/49-es forradalom és szabadságharc ünnepe",
		Regions: []string{"hu"},
		Month:   3,
		Mday:    15,
		Wday:    -1,
	},
	{
		Name:    "A munka ünnepe",
		Regions: []string{"hu"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Az államalapítás ünnepe",
		Regions: []string{"hu"},
		Month:   8,
		Mday:    20,
		Wday:    -1,
	},
	{
		Name:    "1956-os forradalom és szabadságharc ünnepe",
		Regions: []string{"hu"},
		Month:   10,
		Mday:    23,
		Wday:    -1,
	},
	{
		Name:    "Mindenszentek",
		Regions: []string{"hu"},
		Month:   11,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Karácsony",
		Regions: []string{"hu"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
	{
		Name:    "Karácsony",
		Regions: []string{"hu"},
		Month:   12,
		Mday:    26,
		Wday:    -1,
	},
}

var huRegionNames = map[string]string{
	"hu": "Hungary",
}

func init() {
	engine.RegisterCountry("hu", huRules)
	engine.RegisterRegionNames("hu", huRegionNames)
}
