// Code generated by gen-holidays from definitions/ie.yaml@v9.0.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("ie", func() {
	DescribeTable("000_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2008-01-01", "2008-01-01"),
	)

	DescribeTable("001_StPatrickSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Patrick's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Patrick's Day", hols))
	},
		Entry("2008-03-17", "2008-03-17"),
	)

	DescribeTable("002_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2008-03-24", "2008-03-24"),
	)

	DescribeTable("003_MayDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "May Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "May Day", hols))
	},
		Entry("2008-05-05", "2008-05-05"),
	)

	DescribeTable("004_JuneBankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "June Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "June Bank Holiday", hols))
	},
		Entry("2008-06-02", "2008-06-02"),
	)

	DescribeTable("005_AugustBankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "August Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "August Bank Holiday", hols))
	},
		Entry("2008-08-04", "2008-08-04"),
	)

	DescribeTable("006_OctoberBankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "October Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "October Bank Holiday", hols))
	},
		Entry("2008-10-27", "2008-10-27"),
	)

	DescribeTable("007_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2008-12-25", "2008-12-25"),
	)

	DescribeTable("008_StStephenSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Stephen's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Stephen's Day", hols))
	},
		Entry("2008-12-26", "2008-12-26"),
	)

	DescribeTable("009_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2012-01-02", "2012-01-02"),
	)

	DescribeTable("010_StPatrickSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Patrick's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Patrick's Day", hols))
	},
		Entry("2012-03-19", "2012-03-19"),
	)

	DescribeTable("011_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2012-04-09", "2012-04-09"),
	)

	DescribeTable("012_MayDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "May Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "May Day", hols))
	},
		Entry("2012-05-07", "2012-05-07"),
	)

	DescribeTable("013_JuneBankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "June Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "June Bank Holiday", hols))
	},
		Entry("2012-06-04", "2012-06-04"),
	)

	DescribeTable("014_AugustBankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "August Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "August Bank Holiday", hols))
	},
		Entry("2012-08-06", "2012-08-06"),
	)

	DescribeTable("015_OctoberBankHoliday", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "October Bank Holiday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "October Bank Holiday", hols))
	},
		Entry("2012-10-29", "2012-10-29"),
	)

	DescribeTable("016_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2011-12-26", "2011-12-26"),
	)

	DescribeTable("017_StStephenSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Stephen's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Stephen's Day", hols))
	},
		Entry("2011-12-27", "2011-12-27"),
	)

	DescribeTable("018_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2012-12-25", "2012-12-25"),
	)

	DescribeTable("019_StStephenSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Stephen's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Stephen's Day", hols))
	},
		Entry("2012-12-26", "2012-12-26"),
	)

	DescribeTable("020_StStephenSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St. Stephen's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St. Stephen's Day", hols))
	},
		Entry("2015-12-28", "2015-12-28"),
	)

	DescribeTable("021_StBrigidSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St Brigid's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St Brigid's Day", hols))
	},
		Entry("2023-02-06", "2023-02-06"),
		Entry("2024-02-05", "2024-02-05"),
		Entry("2025-02-03", "2025-02-03"),
		Entry("2026-02-02", "2026-02-02"),
		Entry("2028-02-07", "2028-02-07"),
	)

	DescribeTable("022_StBrigidSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St Brigid's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St Brigid's Day", hols))
	},
		Entry("2027-02-01", "2027-02-01"),
	)

	DescribeTable("023_StBrigidSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "St Brigid's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "St Brigid's Day", hols))
	},
		Entry("2030-02-01", "2030-02-01"),
	)

	DescribeTable("024_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2030-02-04", "2030-02-04"),
	)

	DescribeTable("025_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"ie"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2022-02-07", "2022-02-07"),
	)

})
