// Code generated by gen-holidays from definitions/il.yaml@v9.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var ilRules = []definition.HolidayRule{
	{
		Name:    "Exodus from Egypt",
		Regions: []string{"il"},
		Month:   3,
		Mday:    16,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "Exodus from Egypt",
		Regions: []string{"il"},
		Month:   3,
		Mday:    6,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "Exodus from Egypt",
		Regions: []string{"il"},
		Month:   3,
		Mday:    23,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2024}},
		},
	},
	{
		Name:    "Exodus from Egypt",
		Regions: []string{"il"},
		Month:   3,
		Mday:    13,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2025}},
		},
	},
	{
		Name:    "Exodus from Egypt",
		Regions: []string{"il"},
		Month:   3,
		Mday:    2,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2026}},
		},
	},
	{
		Name:    "Exodus from Egypt (day 7)",
		Regions: []string{"il"},
		Month:   3,
		Mday:    22,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "Exodus from Egypt (day 7)",
		Regions: []string{"il"},
		Month:   3,
		Mday:    12,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "Exodus from Egypt (day 7)",
		Regions: []string{"il"},
		Month:   3,
		Mday:    29,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2024}},
		},
	},
	{
		Name:    "Exodus from Egypt (day 7)",
		Regions: []string{"il"},
		Month:   3,
		Mday:    19,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2025}},
		},
	},
	{
		Name:    "Exodus from Egypt (day 7)",
		Regions: []string{"il"},
		Month:   3,
		Mday:    8,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2026}},
		},
	},
	{
		Name:    "Independence Day",
		Regions: []string{"il"},
		Month:   3,
		Mday:    24,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "Independence Day",
		Regions: []string{"il"},
		Month:   3,
		Mday:    20,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2026}},
		},
	},
	{
		Name:    "Independence Day",
		Regions: []string{"il"},
		Month:   4,
		Mday:    4,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "Independence Day",
		Regions: []string{"il"},
		Month:   4,
		Mday:    11,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2024}},
		},
	},
	{
		Name:    "Independence Day",
		Regions: []string{"il"},
		Month:   4,
		Mday:    1,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2025}},
		},
	},
	{
		Name:    "Thanksgiving",
		Regions: []string{"il"},
		Month:   4,
		Mday:    26,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "Thanksgiving",
		Regions: []string{"il"},
		Month:   4,
		Mday:    22,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2026}},
		},
	},
	{
		Name:    "Thanksgiving (day 2)",
		Regions: []string{"il"},
		Month:   4,
		Mday:    27,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "Thanksgiving (day 2)",
		Regions: []string{"il"},
		Month:   4,
		Mday:    23,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2026}},
		},
	},
	{
		Name:    "Thanksgiving",
		Regions: []string{"il"},
		Month:   5,
		Mday:    5,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "Thanksgiving",
		Regions: []string{"il"},
		Month:   5,
		Mday:    12,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2024}},
		},
	},
	{
		Name:    "Thanksgiving",
		Regions: []string{"il"},
		Month:   5,
		Mday:    2,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2025}},
		},
	},
	{
		Name:    "Thanksgiving (day 2)",
		Regions: []string{"il"},
		Month:   5,
		Mday:    6,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "Thanksgiving (day 2)",
		Regions: []string{"il"},
		Month:   5,
		Mday:    13,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2024}},
		},
	},
	{
		Name:    "Thanksgiving (day 2)",
		Regions: []string{"il"},
		Month:   5,
		Mday:    3,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2025}},
		},
	},
	{
		Name:    "Jewish New Year",
		Regions: []string{"il"},
		Month:   9,
		Mday:    26,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "Jewish New Year",
		Regions: []string{"il"},
		Month:   9,
		Mday:    16,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "Jewish New Year",
		Regions: []string{"il"},
		Month:   9,
		Mday:    23,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2025}},
		},
	},
	{
		Name:    "Jewish New Year",
		Regions: []string{"il"},
		Month:   9,
		Mday:    12,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2026}},
		},
	},
	{
		Name:    "2nd New Year's Day",
		Regions: []string{"il"},
		Month:   9,
		Mday:    27,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "2nd New Year's Day",
		Regions: []string{"il"},
		Month:   9,
		Mday:    17,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "2nd New Year's Day",
		Regions: []string{"il"},
		Month:   9,
		Mday:    24,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2025}},
		},
	},
	{
		Name:    "2nd New Year's Day",
		Regions: []string{"il"},
		Month:   9,
		Mday:    13,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2026}},
		},
	},
	{
		Name:    "Day of Atonement",
		Regions: []string{"il"},
		Month:   9,
		Mday:    25,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "Day of Atonement",
		Regions: []string{"il"},
		Month:   9,
		Mday:    21,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2026}},
		},
	},
	{
		Name:    "Feast of Tabernacles",
		Regions: []string{"il"},
		Month:   9,
		Mday:    30,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "Feast of Tabernacles",
		Regions: []string{"il"},
		Month:   9,
		Mday:    26,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2026}},
		},
	},
	{
		Name:    "Jewish New Year",
		Regions: []string{"il"},
		Month:   10,
		Mday:    3,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2024}},
		},
	},
	{
		Name:    "2nd New Year's Day",
		Regions: []string{"il"},
		Month:   10,
		Mday:    4,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2024}},
		},
	},
	{
		Name:    "Day of Atonement",
		Regions: []string{"il"},
		Month:   10,
		Mday:    5,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "Day of Atonement",
		Regions: []string{"il"},
		Month:   10,
		Mday:    12,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2024}},
		},
	},
	{
		Name:    "Day of Atonement",
		Regions: []string{"il"},
		Month:   10,
		Mday:    2,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2025}},
		},
	},
	{
		Name:    "Feast of Tabernacles",
		Regions: []string{"il"},
		Month:   10,
		Mday:    10,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "Feast of Tabernacles",
		Regions: []string{"il"},
		Month:   10,
		Mday:    17,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2024}},
		},
	},
	{
		Name:    "Feast of Tabernacles",
		Regions: []string{"il"},
		Month:   10,
		Mday:    7,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2025}},
		},
	},
	{
		Name:    "Rejoicing of the Torah",
		Regions: []string{"il"},
		Month:   10,
		Mday:    18,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2022}},
		},
	},
	{
		Name:    "Rejoicing of the Torah",
		Regions: []string{"il"},
		Month:   10,
		Mday:    8,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "Rejoicing of the Torah",
		Regions: []string{"il"},
		Month:   10,
		Mday:    25,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2024}},
		},
	},
	{
		Name:    "Rejoicing of the Torah",
		Regions: []string{"il"},
		Month:   10,
		Mday:    15,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2025}},
		},
	},
	{
		Name:    "Rejoicing of the Torah",
		Regions: []string{"il"},
		Month:   10,
		Mday:    4,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2026}},
		},
	},
}

var ilRegionNames = map[string]string{
	"il": "Israel",
}

func init() {
	engine.RegisterCountry("il", ilRules)
	engine.RegisterRegionNames("il", ilRegionNames)
}
