// Code generated by gen-holidays from definitions/il.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("il", func() {
	DescribeTable("000_ExodusFromEgypt", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Exodus from Egypt")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Exodus from Egypt", hols))
	},
		Entry("2024-03-23", "2024-03-23"),
	)

	DescribeTable("001_ExodusFromEgyptDay7", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Exodus from Egypt (day 7)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Exodus from Egypt (day 7)", hols))
	},
		Entry("2023-03-12", "2023-03-12"),
	)

	DescribeTable("002_IndependenceDay", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Independence Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independence Day", hols))
	},
		Entry("2025-04-01", "2025-04-01"),
	)

	DescribeTable("003_Thanksgiving", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Thanksgiving")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Thanksgiving", hols))
	},
		Entry("2026-04-22", "2026-04-22"),
	)

	DescribeTable("004_ThanksgivingDay2", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Thanksgiving (day 2)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Thanksgiving (day 2)", hols))
	},
		Entry("2024-05-13", "2024-05-13"),
	)

	DescribeTable("005_JewishNewYear", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Jewish New Year")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jewish New Year", hols))
	},
		Entry("2023-09-16", "2023-09-16"),
	)

	DescribeTable("006_2ndNewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2nd New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2nd New Year's Day", hols))
	},
		Entry("2025-09-24", "2025-09-24"),
	)

	DescribeTable("007_DayOfAtonement", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Day of Atonement")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Day of Atonement", hols))
	},
		Entry("2026-09-21", "2026-09-21"),
	)

	DescribeTable("008_FeastOfTabernacles", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Feast of Tabernacles")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feast of Tabernacles", hols))
	},
		Entry("2024-10-17", "2024-10-17"),
	)

	DescribeTable("009_RejoicingOfTheTorah", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Rejoicing of the Torah")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Rejoicing of the Torah", hols))
	},
		Entry("2025-10-15", "2025-10-15"),
	)

	DescribeTable("010_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2024-07-09", "2024-07-09"),
	)

	DescribeTable("011_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"il"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2026-08-15", "2026-08-15"),
	)

})
