// Code generated by gen-holidays from definitions/in.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("in", func() {
	DescribeTable("000_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2025-01-01", "2025-01-01"),
	)

	DescribeTable("001_SwamiVivekanandaJayanti", func(s string) {
		opts := holidays.Options{Regions: []string{"in_wb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Swami Vivekananda Jayanti")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Swami Vivekananda Jayanti", hols))
	},
		Entry("2025-01-12", "2025-01-12"),
	)

	DescribeTable("002_MakarSankrantiPongalMaghBihuUttarayanKhichdiSankranti", func(s string) {
		opts := holidays.Options{Regions: []string{"in"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Makar Sankranti / Pongal / Magh Bihu / Uttarayan / Khichdi / Sankranti")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Makar Sankranti / Pongal / Magh Bihu / Uttarayan / Khichdi / Sankranti", hols))
	},
		Entry("2025-01-14", "2025-01-14"),
	)

	DescribeTable("003_NetajiSubhasChandraBoseJayanti", func(s string) {
		opts := holidays.Options{Regions: []string{"in_wb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Netaji Subhas Chandra Bose Jayanti")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Netaji Subhas Chandra Bose Jayanti", hols))
	},
		Entry("2025-01-23", "2025-01-23"),
	)

	DescribeTable("004_RepublicDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Republic Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Republic Day", hols))
	},
		Entry("2025-01-26", "2025-01-26"),
	)

	DescribeTable("005_ChhatrapatiShivajiMaharajJayanti", func(s string) {
		opts := holidays.Options{Regions: []string{"in_mh"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Chhatrapati Shivaji Maharaj Jayanti")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Chhatrapati Shivaji Maharaj Jayanti", hols))
	},
		Entry("2025-02-19", "2025-02-19"),
	)

	DescribeTable("006_ArunachalPradeshStatehoodDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_ar"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Arunachal Pradesh Statehood Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Arunachal Pradesh Statehood Day", hols))
	},
		Entry("2025-02-20", "2025-02-20"),
	)

	DescribeTable("007_MizoramStateDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_mz"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Mizoram State Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Mizoram State Day", hols))
	},
		Entry("2025-02-20", "2025-02-20"),
	)

	DescribeTable("008_BiharDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_br"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bihar Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bihar Day", hols))
	},
		Entry("2025-03-22", "2025-03-22"),
	)

	DescribeTable("009_OdishaDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_od"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Odisha Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Odisha Day", hols))
	},
		Entry("2025-04-01", "2025-04-01"),
	)

	DescribeTable("010_DrBRAmbedkarJayanti", func(s string) {
		opts := holidays.Options{Regions: []string{"in"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dr. B. R. Ambedkar Jayanti")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dr. B. R. Ambedkar Jayanti", hols))
	},
		Entry("2025-04-14", "2025-04-14"),
	)

	DescribeTable("011_HimachalPradeshDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_hp"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Himachal Pradesh Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Himachal Pradesh Day", hols))
	},
		Entry("2025-04-15", "2025-04-15"),
	)

	DescribeTable("012_WestBengalDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_wb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "West Bengal Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "West Bengal Day", hols))
	},
		Entry("2025-04-15", "2025-04-15"),
	)

	DescribeTable("013_LabourDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Labour Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labour Day", hols))
	},
		Entry("2025-05-01", "2025-05-01"),
	)

	DescribeTable("014_GujaratDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_gj"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Gujarat Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Gujarat Day", hols))
	},
		Entry("2025-05-01", "2025-05-01"),
	)

	DescribeTable("015_MaharashtraDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_mh"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Maharashtra Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Maharashtra Day", hols))
	},
		Entry("2025-05-01", "2025-05-01"),
	)

	DescribeTable("016_RabindranathTagoreJayanti", func(s string) {
		opts := holidays.Options{Regions: []string{"in_wb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Rabindranath Tagore Jayanti")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Rabindranath Tagore Jayanti", hols))
	},
		Entry("2025-05-07", "2025-05-07"),
	)

	DescribeTable("017_SikkimStateDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_sk"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sikkim State Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sikkim State Day", hols))
	},
		Entry("2025-05-16", "2025-05-16"),
	)

	DescribeTable("018_TelanganaFormationDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_ts"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Telangana Formation Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Telangana Formation Day", hols))
	},
		Entry("2025-06-02", "2025-06-02"),
	)

	DescribeTable("019_MartyrsDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_jh"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Martyrs' Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Martyrs' Day", hols))
	},
		Entry("2025-07-13", "2025-07-13"),
	)

	DescribeTable("020_IndependenceDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Independence day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independence day", hols))
	},
		Entry("2025-08-15", "2025-08-15"),
	)

	DescribeTable("021_PuducherryDeJureTransferDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_py"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Puducherry De Jure Transfer Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Puducherry De Jure Transfer Day", hols))
	},
		Entry("2025-08-16", "2025-08-16"),
	)

	DescribeTable("022_SreeNarayanaGuruJayanti", func(s string) {
		opts := holidays.Options{Regions: []string{"in_kl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sree Narayana Guru Jayanti")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sree Narayana Guru Jayanti", hols))
	},
		Entry("2025-08-20", "2025-08-20"),
	)

	DescribeTable("023_HyderabadKarnatakaLiberationDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_ka"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Hyderabad-Karnataka Liberation Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Hyderabad-Karnataka Liberation Day", hols))
	},
		Entry("2025-09-17", "2025-09-17"),
	)

	DescribeTable("024_MahatmaGandhiJayanti", func(s string) {
		opts := holidays.Options{Regions: []string{"in"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Mahatma Gandhi Jayanti")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Mahatma Gandhi Jayanti", hols))
	},
		Entry("2025-10-02", "2025-10-02"),
	)

	DescribeTable("025_JammuAndKashmirAssociationDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_jk"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Jammu and Kashmir Association Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jammu and Kashmir Association Day", hols))
	},
		Entry("2025-10-26", "2025-10-26"),
	)

	DescribeTable("026_SardarVallabhbhaiPatelJayanti", func(s string) {
		opts := holidays.Options{Regions: []string{"in_gj"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sardar Vallabhbhai Patel Jayanti")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sardar Vallabhbhai Patel Jayanti", hols))
	},
		Entry("2025-10-31", "2025-10-31"),
	)

	DescribeTable("027_AndhraPradeshDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_ap"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Andhra Pradesh Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Andhra Pradesh Day", hols))
	},
		Entry("2025-11-01", "2025-11-01"),
	)

	DescribeTable("028_ChhattisgarhRajyotsava", func(s string) {
		opts := holidays.Options{Regions: []string{"in_cg"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Chhattisgarh Rajyotsava")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Chhattisgarh Rajyotsava", hols))
	},
		Entry("2025-11-01", "2025-11-01"),
	)

	DescribeTable("029_HaryanaDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_hr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Haryana Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Haryana Day", hols))
	},
		Entry("2025-11-01", "2025-11-01"),
	)

	DescribeTable("030_KannadaRajyothsava", func(s string) {
		opts := holidays.Options{Regions: []string{"in_ka"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Kannada Rajyothsava")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Kannada Rajyothsava", hols))
	},
		Entry("2025-11-01", "2025-11-01"),
	)

	DescribeTable("031_KeralaDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_kl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Kerala Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Kerala Day", hols))
	},
		Entry("2025-11-01", "2025-11-01"),
	)

	DescribeTable("032_MadhyaPradeshDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_mp"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Madhya Pradesh Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Madhya Pradesh Day", hols))
	},
		Entry("2025-11-01", "2025-11-01"),
	)

	DescribeTable("033_PunjabDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_pb"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Punjab Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Punjab Day", hols))
	},
		Entry("2025-11-01", "2025-11-01"),
	)

	DescribeTable("034_PuducherryLiberationDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_py"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Puducherry Liberation Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Puducherry Liberation Day", hols))
	},
		Entry("2025-11-01", "2025-11-01"),
	)

	DescribeTable("035_NagalandStateInaugurationDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_nl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Nagaland State Inauguration Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nagaland State Inauguration Day", hols))
	},
		Entry("2025-12-01", "2025-12-01"),
	)

	DescribeTable("036_AsomDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_as"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Asom Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Asom Day", hols))
	},
		Entry("2025-12-02", "2025-12-02"),
	)

	DescribeTable("037_GoaLiberationDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in_ga"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Goa Liberation Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Goa Liberation Day", hols))
	},
		Entry("2025-12-19", "2025-12-19"),
	)

	DescribeTable("038_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"in"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2025-12-25", "2025-12-25"),
	)

	DescribeTable("039_GoodFriday", func(s string) {
		opts := holidays.Options{Regions: []string{"in"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Good Friday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols))
	},
		Entry("2025-04-18", "2025-04-18"),
	)

	DescribeTable("040_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"in"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2025-01-04", "2025-01-04"),
		Entry("2025-01-18", "2025-01-18"),
	)

})
