// Code generated by gen-holidays from definitions/ke.yaml@v9.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var keRules = []definition.HolidayRule{
	{
		Name:             "Good Friday",
		Regions:          []string{"ke"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:             "Easter Monday",
		Regions:          []string{"ke"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:     "New Year's Day",
		Regions:  []string{"ke"},
		Month:    1,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:     "Labour Day",
		Regions:  []string{"ke"},
		Month:    5,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:     "Madaraka Day",
		Regions:  []string{"ke"},
		Month:    6,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:     "Huduma Day",
		Regions:  []string{"ke"},
		Month:    10,
		Mday:     10,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:     "Mashujaa Day",
		Regions:  []string{"ke"},
		Month:    10,
		Mday:     20,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:     "Jamhuri Day",
		Regions:  []string{"ke"},
		Month:    12,
		Mday:     12,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:     "Christmas Day",
		Regions:  []string{"ke"},
		Month:    12,
		Mday:     25,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:     "Utamaduni Day",
		Regions:  []string{"ke"},
		Month:    12,
		Mday:     26,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
}

var keRegionNames = map[string]string{
	"ke": "Kenya",
}

func init() {
	engine.RegisterCountry("ke", keRules)
	engine.RegisterRegionNames("ke", keRegionNames)
}
