// Code generated by gen-holidays from definitions/li.yaml@v9.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var liRules = []definition.HolidayRule{
	{
		Name:             "Fasnachtsdienstag",
		Regions:          []string{"li"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -47,
	},
	{
		Name:             "Karfreitag",
		Regions:          []string{"li"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:         "Ostern",
		Regions:      []string{"li"},
		Month:        0,
		Wday:         -1,
		Function:     "easter",
		FunctionArgs: []string{"year"},
		Type:         definition.Informal,
	},
	{
		Name:             "Ostermontag",
		Regions:          []string{"li"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:             "Auffahrt",
		Regions:          []string{"li"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 39,
	},
	{
		Name:             "Pfingstmontag",
		Regions:          []string{"li"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 50,
	},
	{
		Name:             "Fronleichnam",
		Regions:          []string{"li"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 60,
	},
	{
		Name:    "Neujahrstag",
		Regions: []string{"li"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Heilige Drei Könige",
		Regions: []string{"li", "li"},
		Month:   1,
		Mday:    6,
		Wday:    -1,
	},
	{
		Name:    "Maria Lichtmess",
		Regions: []string{"li"},
		Month:   2,
		Mday:    2,
		Wday:    -1,
	},
	{
		Name:    "St. Josef",
		Regions: []string{"li"},
		Month:   3,
		Mday:    19,
		Wday:    -1,
	},
	{
		Name:    "Tag der Arbeit",
		Regions: []string{"li"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Staatsfeiertag",
		Regions: []string{"li"},
		Month:   8,
		Mday:    15,
		Wday:    -1,
	},
	{
		Name:    "Maria Geburt",
		Regions: []string{"li"},
		Month:   9,
		Mday:    8,
		Wday:    -1,
	},
	{
		Name:    "Allerheiligen",
		Regions: []string{"li"},
		Month:   11,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Maria Empfängnis",
		Regions: []string{"li"},
		Month:   12,
		Mday:    8,
		Wday:    -1,
	},
	{
		Name:    "Heilig Abend",
		Regions: []string{"li"},
		Month:   12,
		Mday:    24,
		Wday:    -1,
	},
	{
		Name:    "Weihnachten",
		Regions: []string{"li"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
	{
		Name:    "Stefanstag",
		Regions: []string{"li"},
		Month:   12,
		Mday:    26,
		Wday:    -1,
	},
	{
		Name:    "Silvester",
		Regions: []string{"li"},
		Month:   12,
		Mday:    31,
		Wday:    -1,
	},
}

var liRegionNames = map[string]string{
	"li": "Liechtenstein",
}

func init() {
	engine.RegisterCountry("li", liRules)
	engine.RegisterRegionNames("li", liRegionNames)
}
