// Code generated by gen-holidays from definitions/li.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("li", func() {
	DescribeTable("000_Neujahrstag", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Neujahrstag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Neujahrstag", hols))
	},
		Entry("2009-01-01", "2009-01-01"),
	)

	DescribeTable("001_Fasnachtsdienstag", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fasnachtsdienstag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fasnachtsdienstag", hols))
	},
		Entry("2011-03-08", "2011-03-08"),
	)

	DescribeTable("002_Karfreitag", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Karfreitag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Karfreitag", hols))
	},
		Entry("2009-04-10", "2009-04-10"),
	)

	DescribeTable("003_Ostern", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ostern")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ostern", hols))
	},
		Entry("2009-04-12", "2009-04-12"),
	)

	DescribeTable("004_Ostermontag", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ostermontag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ostermontag", hols))
	},
		Entry("2009-04-13", "2009-04-13"),
	)

	DescribeTable("005_Auffahrt", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Auffahrt")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Auffahrt", hols))
	},
		Entry("2009-05-21", "2009-05-21"),
	)

	DescribeTable("006_Pfingstmontag", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Pfingstmontag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Pfingstmontag", hols))
	},
		Entry("2009-06-01", "2009-06-01"),
	)

	DescribeTable("007_Weihnachten", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Weihnachten")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Weihnachten", hols))
	},
		Entry("2009-12-25", "2009-12-25"),
	)

	DescribeTable("008_Stefanstag", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Stefanstag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Stefanstag", hols))
	},
		Entry("2009-12-26", "2009-12-26"),
	)

	DescribeTable("009_Fronleichnam", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fronleichnam")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fronleichnam", hols))
	},
		Entry("2009-06-11", "2009-06-11"),
	)

	DescribeTable("010_Staatsfeiertag", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Staatsfeiertag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Staatsfeiertag", hols))
	},
		Entry("2009-08-15", "2009-08-15"),
	)

	DescribeTable("011_Allerheiligen", func(s string) {
		opts := holidays.Options{Regions: []string{"li"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Allerheiligen")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Allerheiligen", hols))
	},
		Entry("2009-11-01", "2009-11-01"),
	)

})
