// Code generated by gen-holidays from definitions/lu.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("lu", func() {
	DescribeTable("000_Neijoerschdag", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Neijoerschdag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Neijoerschdag", hols))
	},
		Entry("2008-01-01", "2008-01-01"),
	)

	DescribeTable("001_Ouschterméindeg", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ouschterméindeg")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ouschterméindeg", hols))
	},
		Entry("2008-03-24", "2008-03-24"),
	)

	DescribeTable("002_ChristiHimmelfaart", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christi Himmelfaart")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christi Himmelfaart", hols))
	},
		Entry("2008-05-01", "2008-05-01"),
	)

	DescribeTable("003_Nationalfeierdag", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Nationalfeierdag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nationalfeierdag", hols))
	},
		Entry("2008-06-23", "2008-06-23"),
	)

	DescribeTable("004_Léiffrawëschdag", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Léiffrawëschdag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Léiffrawëschdag", hols))
	},
		Entry("2008-08-15", "2008-08-15"),
	)

	DescribeTable("005_Allerhellgen", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Allerhellgen")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Allerhellgen", hols))
	},
		Entry("2008-11-01", "2008-11-01"),
	)

	DescribeTable("006_Chrëschtdag", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Chrëschtdag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Chrëschtdag", hols))
	},
		Entry("2008-12-25", "2008-12-25"),
	)

	DescribeTable("007_Stiefesdag", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Stiefesdag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Stiefesdag", hols))
	},
		Entry("2008-12-26", "2008-12-26"),
	)

	DescribeTable("008_Péngschtméindeg", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Péngschtméindeg")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Péngschtméindeg", hols))
	},
		Entry("2008-05-12", "2008-05-12"),
	)

	DescribeTable("009_DagVunDerAarbecht", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dag vun der Aarbecht")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dag vun der Aarbecht", hols))
	},
		Entry("2019-05-01", "2019-05-01"),
	)

	DescribeTable("010_Europadag", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Europadag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Europadag", hols))
	},
		Entry("2019-05-09", "2019-05-09"),
	)

	DescribeTable("011_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"lu"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2018-05-09", "2018-05-09"),
	)

})
