// Code generated by gen-holidays from definitions/lv.yaml@v9.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var lvRules = []definition.HolidayRule{
	{
		Name:             "Lielā Piektdiena",
		Regions:          []string{"lv"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:         "Pirmās Lieldienas",
		Regions:      []string{"lv"},
		Month:        0,
		Wday:         -1,
		Function:     "easter",
		FunctionArgs: []string{"year"},
	},
	{
		Name:             "Otrās Lieldienas",
		Regions:          []string{"lv"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:             "Vasarsvētki",
		Regions:          []string{"lv"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 49,
	},
	{
		Name:         "Vispārējo latviešu Dziesmu un deju svētku noslēguma diena",
		Regions:      []string{"lv"},
		Month:        0,
		Wday:         -1,
		Function:     "lv_song_and_dance_festival_end_date",
		FunctionArgs: []string{"year"},
		Observed:     "to_monday_if_weekend",
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2018}},
		},
	},
	{
		Name:    "Jaungada diena",
		Regions: []string{"lv"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Darba svētki, Latvijas Republikas Satversmes sapulces sasaukšanas diena",
		Regions: []string{"lv"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:     "Latvijas Republikas Neatkarības atjaunošanas diena",
		Regions:  []string{"lv"},
		Month:    5,
		Mday:     4,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:    "Mātes diena",
		Regions: []string{"lv"},
		Month:   5,
		Wday:    0,
		Week:    2,
	},
	{
		Name:    "Diena, kad Latvijas hokeja komanda ieguva bronzas medaļu 2023. gada Pasaules hokeja čempionātā",
		Regions: []string{"lv"},
		Month:   5,
		Mday:    29,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2023}},
		},
	},
	{
		Name:    "Līgo diena",
		Regions: []string{"lv"},
		Month:   6,
		Mday:    23,
		Wday:    -1,
	},
	{
		Name:    "Jāņu diena",
		Regions: []string{"lv"},
		Month:   6,
		Mday:    24,
		Wday:    -1,
	},
	{
		Name:    "Viņa Svētības pāvesta Franciska pastorālās vizītes Latvijā diena",
		Regions: []string{"lv"},
		Month:   9,
		Mday:    24,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{2018}},
		},
	},
	{
		Name:     "Latvijas Republikas Proklamēšanas diena",
		Regions:  []string{"lv"},
		Month:    11,
		Mday:     18,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:    "Ziemassvētku vakars",
		Regions: []string{"lv"},
		Month:   12,
		Mday:    24,
		Wday:    -1,
	},
	{
		Name:    "Pirmie Ziemassvētki",
		Regions: []string{"lv"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
	{
		Name:    "Otrie Ziemassvētki",
		Regions: []string{"lv"},
		Month:   12,
		Mday:    26,
		Wday:    -1,
	},
	{
		Name:    "Vecgada diena",
		Regions: []string{"lv"},
		Month:   12,
		Mday:    31,
		Wday:    -1,
	},
}

var lvRegionNames = map[string]string{
	"lv": "Latvia",
}

func init() {
	engine.RegisterCountry("lv", lvRules)
	engine.RegisterRegionNames("lv", lvRegionNames)
}
