// Code generated by gen-holidays from definitions/ma.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var maRules = []definition.HolidayRule{
	{
		Name:    "Ras l' âm",
		Regions: []string{"ma"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Takdim watikat al-istiqlal",
		Regions: []string{"ma"},
		Month:   1,
		Mday:    11,
		Wday:    -1,
	},
	{
		Name:    "Eid Ash-Shughl",
		Regions: []string{"ma"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Eid Al-Ârch",
		Regions: []string{"ma"},
		Month:   7,
		Mday:    30,
		Wday:    -1,
	},
	{
		Name:    "Zikra Oued Ed-Dahab",
		Regions: []string{"ma"},
		Month:   8,
		Mday:    14,
		Wday:    -1,
	},
	{
		Name:    "Thawrat al malik wa shâab",
		Regions: []string{"ma"},
		Month:   8,
		Mday:    20,
		Wday:    -1,
	},
	{
		Name:    "Eid Al Milad",
		Regions: []string{"ma"},
		Month:   8,
		Mday:    21,
		Wday:    -1,
	},
	{
		Name:    "Eid Al Massira Al Khadra",
		Regions: []string{"ma"},
		Month:   11,
		Mday:    6,
		Wday:    -1,
	},
	{
		Name:    "Eid Al Istiqulal",
		Regions: []string{"ma"},
		Month:   11,
		Mday:    18,
		Wday:    -1,
	},
}

var maRegionNames = map[string]string{
	"ma": "Morocco",
}

func init() {
	engine.RegisterCountry("ma", maRules)
	engine.RegisterRegionNames("ma", maRegionNames)
}
