// Code generated by gen-holidays from definitions/ma.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("ma", func() {
	DescribeTable("000_RasLÂm", func(s string) {
		opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ras l' âm")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ras l' âm", hols))
	},
		Entry("2007-01-01", "2007-01-01"),
	)

	DescribeTable("001_TakdimWatikatAlIstiqlal", func(s string) {
		opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Takdim watikat al-istiqlal")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Takdim watikat al-istiqlal", hols))
	},
		Entry("2007-01-11", "2007-01-11"),
	)

	DescribeTable("002_EidAshShughl", func(s string) {
		opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Eid Ash-Shughl")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Eid Ash-Shughl", hols))
	},
		Entry("2007-05-01", "2007-05-01"),
	)

	DescribeTable("003_EidAlÂrch", func(s string) {
		opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Eid Al-Ârch")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Eid Al-Ârch", hols))
	},
		Entry("2007-07-30", "2007-07-30"),
	)

	DescribeTable("004_ZikraOuedEdDahab", func(s string) {
		opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Zikra Oued Ed-Dahab")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Zikra Oued Ed-Dahab", hols))
	},
		Entry("2007-08-14", "2007-08-14"),
	)

	DescribeTable("005_ThawratAlMalikWaShâab", func(s string) {
		opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Thawrat al malik wa shâab")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Thawrat al malik wa shâab", hols))
	},
		Entry("2007-08-20", "2007-08-20"),
	)

	DescribeTable("006_EidAlMilad", func(s string) {
		opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Eid Al Milad")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Eid Al Milad", hols))
	},
		Entry("2007-08-21", "2007-08-21"),
	)

	DescribeTable("007_EidAlMassiraAlKhadra", func(s string) {
		opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Eid Al Massira Al Khadra")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Eid Al Massira Al Khadra", hols))
	},
		Entry("2007-11-06", "2007-11-06"),
	)

	DescribeTable("008_EidAlIstiqulal", func(s string) {
		opts := holidays.Options{Regions: []string{"ma"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Eid Al Istiqulal")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Eid Al Istiqulal", hols))
	},
		Entry("2007-11-18", "2007-11-18"),
	)

})
