// Code generated by gen-holidays from definitions/mc.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("mc", func() {
	DescribeTable("000_JourDeLAn", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Jour de l'an")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jour de l'an", hols))
	},
		Entry("2026-01-01", "2026-01-01"),
	)

	DescribeTable("001_SainteDévote", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sainte Dévote")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sainte Dévote", hols))
	},
		Entry("2026-01-27", "2026-01-27"),
	)

	DescribeTable("002_LundiDePâques", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Lundi de Pâques")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi de Pâques", hols))
	},
		Entry("2026-04-06", "2026-04-06"),
	)

	DescribeTable("003_FêteDuTravail", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fête du Travail")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête du Travail", hols))
	},
		Entry("2026-05-01", "2026-05-01"),
	)

	DescribeTable("004_Ascension", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ascension")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ascension", hols))
	},
		Entry("2026-05-14", "2026-05-14"),
	)

	DescribeTable("005_LundiDePentecôte", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Lundi de Pentecôte")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Lundi de Pentecôte", hols))
	},
		Entry("2026-05-25", "2026-05-25"),
	)

	DescribeTable("006_FêteDieu", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fête Dieu")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête Dieu", hols))
	},
		Entry("2026-06-04", "2026-06-04"),
	)

	DescribeTable("007_Assomption", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Assomption")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Assomption", hols))
	},
		Entry("2026-08-15", "2026-08-15"),
	)

	DescribeTable("008_Toussaint", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Toussaint")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Toussaint", hols))
	},
		Entry("2026-11-01", "2026-11-01"),
	)

	DescribeTable("009_FêteDuPrince", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fête du Prince")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête du Prince", hols))
	},
		Entry("2026-11-19", "2026-11-19"),
	)

	DescribeTable("010_ImmaculéeConception", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Immaculée Conception")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Immaculée Conception", hols))
	},
		Entry("2026-12-08", "2026-12-08"),
	)

	DescribeTable("011_Noël", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Noël")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Noël", hols))
	},
		Entry("2026-12-25", "2026-12-25"),
	)

	DescribeTable("012_ImmaculéeConception", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Immaculée Conception")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Immaculée Conception", hols))
	},
		Entry("2024-12-08", "2024-12-08"),
	)

	DescribeTable("013_ImmaculéeConception", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Immaculée Conception")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Immaculée Conception", hols))
	},
		Entry("2024-12-09", "2024-12-09"),
	)

	DescribeTable("014_Toussaint", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Toussaint")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Toussaint", hols))
	},
		Entry("2026-11-01", "2026-11-01"),
	)

	DescribeTable("015_Toussaint", func(s string) {
		opts := holidays.Options{Regions: []string{"mc"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Toussaint")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Toussaint", hols))
	},
		Entry("2026-11-02", "2026-11-02"),
	)

})
