// Code generated by gen-holidays from definitions/mt_en.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("mt_en", func() {
	DescribeTable("000_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2017-1-1", "2017-1-1"),
	)

	DescribeTable("001_FeastOfSaintPaulSShipwreckInMalta", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Feast of Saint Paul's Shipwreck in Malta")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feast of Saint Paul's Shipwreck in Malta", hols))
	},
		Entry("2017-2-10", "2017-2-10"),
	)

	DescribeTable("002_FeastOfSaintJoseph", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Feast of Saint Joseph")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feast of Saint Joseph", hols))
	},
		Entry("2017-3-19", "2017-3-19"),
	)

	DescribeTable("003_FreedomDay", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Freedom Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Freedom Day", hols))
	},
		Entry("2017-3-31", "2017-3-31"),
	)

	DescribeTable("004_WorkerSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Worker's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Worker's Day", hols))
	},
		Entry("2017-5-1", "2017-5-1"),
	)

	DescribeTable("005_SetteGiugno", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sette Giugno")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sette Giugno", hols))
	},
		Entry("2017-6-7", "2017-6-7"),
	)

	DescribeTable("006_FeastOfSaintPeterSaintPaul", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Feast of Saint Peter & Saint Paul")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feast of Saint Peter & Saint Paul", hols))
	},
		Entry("2017-6-29", "2017-6-29"),
	)

	DescribeTable("007_FeastOfTheAssumptionOfOurLady", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Feast of the Assumption of Our Lady")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feast of the Assumption of Our Lady", hols))
	},
		Entry("2017-8-15", "2017-8-15"),
	)

	DescribeTable("008_VictoryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Victory Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Victory Day", hols))
	},
		Entry("2017-9-8", "2017-9-8"),
	)

	DescribeTable("009_IndependenceDay", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Independence Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independence Day", hols))
	},
		Entry("2017-9-21", "2017-9-21"),
	)

	DescribeTable("010_FeastOfTheImmaculateConception", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Feast of the Immaculate Conception")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Feast of the Immaculate Conception", hols))
	},
		Entry("2017-12-8", "2017-12-8"),
	)

	DescribeTable("011_RepublicDay", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Republic Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Republic Day", hols))
	},
		Entry("2017-12-13", "2017-12-13"),
	)

	DescribeTable("012_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2017-12-25", "2017-12-25"),
	)

	DescribeTable("013_GoodFriday", func(s string) {
		opts := holidays.Options{Regions: []string{"mt_en"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Good Friday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols))
	},
		Entry("2017-4-14", "2017-4-14"),
		Entry("2018-3-30", "2018-3-30"),
		Entry("2019-4-19", "2019-4-19"),
	)

})
