// Code generated by gen-holidays from definitions/mx.yaml@v9.0.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("mx", func() {
	DescribeTable("000_AñoNuevo", func(s string) {
		opts := holidays.Options{Regions: []string{"mx"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Año nuevo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Año nuevo", hols))
	},
		Entry("2007-01-01", "2007-01-01"),
	)

	DescribeTable("001_DíaDeLaConstitución", func(s string) {
		opts := holidays.Options{Regions: []string{"mx"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Constitución")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Constitución", hols))
	},
		Entry("2007-02-05", "2007-02-05"),
	)

	DescribeTable("002_DíaDelTrabajo", func(s string) {
		opts := holidays.Options{Regions: []string{"mx"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día del Trabajo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día del Trabajo", hols))
	},
		Entry("2007-05-01", "2007-05-01"),
	)

	DescribeTable("003_CincoDeMayo", func(s string) {
		opts := holidays.Options{Regions: []string{"mx"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Cinco de Mayo")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Cinco de Mayo", hols))
	},
		Entry("2007-05-05", "2007-05-05"),
	)

	DescribeTable("004_GritoDeDolores", func(s string) {
		opts := holidays.Options{Regions: []string{"mx"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Grito de Dolores")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Grito de Dolores", hols))
	},
		Entry("2007-09-15", "2007-09-15"),
	)

	DescribeTable("005_DíaDeLaIndependencia", func(s string) {
		opts := holidays.Options{Regions: []string{"mx"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Independencia")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Independencia", hols))
	},
		Entry("2007-09-16", "2007-09-16"),
	)

	DescribeTable("006_TodosLosSantos", func(s string) {
		opts := holidays.Options{Regions: []string{"mx"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Todos los Santos")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Todos los Santos", hols))
	},
		Entry("2007-11-01", "2007-11-01"),
	)

	DescribeTable("007_LosFielesDifuntos", func(s string) {
		opts := holidays.Options{Regions: []string{"mx"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Los Fieles Difuntos")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Los Fieles Difuntos", hols))
	},
		Entry("2007-11-02", "2007-11-02"),
	)

	DescribeTable("008_DíaDeLaRevolución", func(s string) {
		opts := holidays.Options{Regions: []string{"mx"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Día de la Revolución")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Día de la Revolución", hols))
	},
		Entry("2007-11-19", "2007-11-19"),
	)

	DescribeTable("009_Navidad", func(s string) {
		opts := holidays.Options{Regions: []string{"mx"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Navidad")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Navidad", hols))
	},
		Entry("2007-12-25", "2007-12-25"),
	)

})
