// Code generated by gen-holidays from definitions/nerc.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("nerc", func() {
	DescribeTable("000_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nerc"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2013-01-01", "2013-01-01"),
	)

	DescribeTable("001_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nerc"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2017-01-02", "2017-01-02"),
	)

	DescribeTable("002_MemorialDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nerc"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Memorial Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Memorial Day", hols))
	},
		Entry("2013-05-27", "2013-05-27"),
	)

	DescribeTable("003_IndependenceDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nerc"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Independence Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independence Day", hols))
	},
		Entry("2013-07-04", "2013-07-04"),
	)

	DescribeTable("004_IndependenceDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nerc"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Independence Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independence Day", hols))
	},
		Entry("2010-07-05", "2010-07-05"),
	)

	DescribeTable("005_LaborDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nerc"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Labor Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labor Day", hols))
	},
		Entry("2013-09-02", "2013-09-02"),
	)

	DescribeTable("006_Thanksgiving", func(s string) {
		opts := holidays.Options{Regions: []string{"nerc"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Thanksgiving")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Thanksgiving", hols))
	},
		Entry("2013-11-28", "2013-11-28"),
	)

	DescribeTable("007_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nerc"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2013-12-25", "2013-12-25"),
	)

	DescribeTable("008_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nerc"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2011-12-26", "2011-12-26"),
	)

})
