// Code generated by gen-holidays from definitions/nerc.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var nercRules = []definition.HolidayRule{
	{
		Name:     "New Year's Day",
		Regions:  []string{"nerc"},
		Month:    1,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:    "Memorial Day",
		Regions: []string{"nerc"},
		Month:   5,
		Wday:    1,
		Week:    -1,
	},
	{
		Name:     "Independence Day",
		Regions:  []string{"nerc"},
		Month:    7,
		Mday:     4,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:    "Labor Day",
		Regions: []string{"nerc"},
		Month:   9,
		Wday:    1,
		Week:    1,
	},
	{
		Name:    "Thanksgiving",
		Regions: []string{"nerc"},
		Month:   11,
		Wday:    4,
		Week:    4,
	},
	{
		Name:     "Christmas Day",
		Regions:  []string{"nerc"},
		Month:    12,
		Mday:     25,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
}

var nercRegionNames = map[string]string{
	"nerc": "North American Electric Reliability Corporation",
}

func init() {
	engine.RegisterCountry("nerc", nercRules)
	engine.RegisterRegionNames("nerc", nercRegionNames)
}
