// Code generated by gen-holidays from definitions/ng.yaml@v9.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var ngRules = []definition.HolidayRule{
	{
		Name:             "Good Friday",
		Regions:          []string{"ng"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:             "Easter Monday",
		Regions:          []string{"ng"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:     "New Year's Day",
		Regions:  []string{"ng"},
		Month:    1,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:     "Workers' Day",
		Regions:  []string{"ng"},
		Month:    5,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:    "Children's Day",
		Regions: []string{"ng"},
		Month:   5,
		Mday:    27,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Democracy Day",
		Regions: []string{"ng"},
		Month:   6,
		Mday:    12,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2018}},
		},
	},
	{
		Name:     "Independence Day",
		Regions:  []string{"ng"},
		Month:    10,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:     "Christmas Day",
		Regions:  []string{"ng"},
		Month:    12,
		Mday:     25,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:     "Boxing Day",
		Regions:  []string{"ng"},
		Month:    12,
		Mday:     26,
		Wday:     -1,
		Observed: "to_weekday_if_boxing_weekend",
	},
}

var ngRegionNames = map[string]string{
	"ng": "Nigeria",
}

func init() {
	engine.RegisterCountry("ng", ngRules)
	engine.RegisterRegionNames("ng", ngRegionNames)
}
