// Code generated by gen-holidays from definitions/nl.yaml@v9.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var nlRules = []definition.HolidayRule{
	{
		Name:             "Goede Vrijdag",
		Regions:          []string{"nl"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
		Type:             definition.Informal,
	},
	{
		Name:         "Eerste Paasdag",
		Regions:      []string{"nl"},
		Month:        0,
		Wday:         -1,
		Function:     "easter",
		FunctionArgs: []string{"year"},
	},
	{
		Name:             "Tweede Paasdag",
		Regions:          []string{"nl"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:             "Hemelvaartsdag",
		Regions:          []string{"nl"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 39,
	},
	{
		Name:             "Eerste Pinksterdag",
		Regions:          []string{"nl"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 49,
	},
	{
		Name:             "Tweede Pinksterdag",
		Regions:          []string{"nl"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 50,
	},
	{
		Name:    "Nieuwjaarsdag",
		Regions: []string{"nl"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Koningsdag",
		Regions: []string{"nl"},
		Month:   4,
		Mday:    27,
		Wday:    -1,
	},
	{
		Name:    "Dodenherdenking",
		Regions: []string{"nl"},
		Month:   5,
		Mday:    4,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Bevrijdingsdag",
		Regions: []string{"nl"},
		Month:   5,
		Mday:    5,
		Wday:    -1,
	},
	{
		Name:    "Sinterklaas",
		Regions: []string{"nl"},
		Month:   12,
		Mday:    5,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Eerste Kerstdag",
		Regions: []string{"nl"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
	{
		Name:    "Tweede Kerstdag",
		Regions: []string{"nl"},
		Month:   12,
		Mday:    26,
		Wday:    -1,
	},
}

var nlRegionNames = map[string]string{
	"nl": "Netherlands",
}

func init() {
	engine.RegisterCountry("nl", nlRules)
	engine.RegisterRegionNames("nl", nlRegionNames)
}
