// Code generated by gen-holidays from definitions/no.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var noRules = []definition.HolidayRule{
	{
		Name:             "Fastelavn",
		Regions:          []string{"no"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -49,
		Type:             definition.Informal,
	},
	{
		Name:             "Palmesøndag",
		Regions:          []string{"no"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -7,
	},
	{
		Name:             "Skjærtorsdag",
		Regions:          []string{"no"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -3,
	},
	{
		Name:             "Langfredag",
		Regions:          []string{"no"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:         "1. påskedag",
		Regions:      []string{"no"},
		Month:        0,
		Wday:         -1,
		Function:     "easter",
		FunctionArgs: []string{"year"},
	},
	{
		Name:             "2. påskedag",
		Regions:          []string{"no"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 1,
	},
	{
		Name:             "Kristi Himmelfartsdag",
		Regions:          []string{"no"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 39,
	},
	{
		Name:             "1. pinsedag",
		Regions:          []string{"no"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 49,
	},
	{
		Name:             "2. pinsedag",
		Regions:          []string{"no"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 50,
	},
	{
		Name:    "Nyttårsdag",
		Regions: []string{"no"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "1. mai",
		Regions: []string{"no"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "17. mai",
		Regions: []string{"no"},
		Month:   5,
		Mday:    17,
		Wday:    -1,
	},
	{
		Name:    "Julaften",
		Regions: []string{"no"},
		Month:   12,
		Mday:    24,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "1. juledag",
		Regions: []string{"no"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
	{
		Name:    "2. juledag",
		Regions: []string{"no"},
		Month:   12,
		Mday:    26,
		Wday:    -1,
	},
	{
		Name:    "Nyttårsaften",
		Regions: []string{"no"},
		Month:   12,
		Mday:    31,
		Wday:    -1,
		Type:    definition.Informal,
	},
}

var noRegionNames = map[string]string{
	"no": "Norway",
}

func init() {
	engine.RegisterCountry("no", noRules)
	engine.RegisterRegionNames("no", noRegionNames)
}
