// Code generated by gen-holidays from definitions/no.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("no", func() {
	DescribeTable("000_Nyttårsdag", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Nyttårsdag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nyttårsdag", hols))
	},
		Entry("2010-01-01", "2010-01-01"),
	)

	DescribeTable("001_1Mai", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "1. mai")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. mai", hols))
	},
		Entry("2010-05-01", "2010-05-01"),
	)

	DescribeTable("002_17Mai", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "17. mai")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "17. mai", hols))
	},
		Entry("2010-05-17", "2010-05-17"),
	)

	DescribeTable("003_Julaften", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Julaften")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Julaften", hols))
	},
		Entry("2010-12-24", "2010-12-24"),
	)

	DescribeTable("004_1Juledag", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "1. juledag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. juledag", hols))
	},
		Entry("2010-12-25", "2010-12-25"),
	)

	DescribeTable("005_2Juledag", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2. juledag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. juledag", hols))
	},
		Entry("2010-12-26", "2010-12-26"),
	)

	DescribeTable("006_Nyttårsaften", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Nyttårsaften")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nyttårsaften", hols))
	},
		Entry("2010-12-31", "2010-12-31"),
	)

	DescribeTable("007_Fastelavn", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fastelavn")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fastelavn", hols))
	},
		Entry("2010-02-14", "2010-02-14"),
	)

	DescribeTable("008_Palmesøndag", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Palmesøndag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Palmesøndag", hols))
	},
		Entry("2010-03-28", "2010-03-28"),
	)

	DescribeTable("009_Skjærtorsdag", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Skjærtorsdag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Skjærtorsdag", hols))
	},
		Entry("2010-04-01", "2010-04-01"),
	)

	DescribeTable("010_Langfredag", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Langfredag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Langfredag", hols))
	},
		Entry("2010-04-02", "2010-04-02"),
	)

	DescribeTable("011_1Påskedag", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "1. påskedag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. påskedag", hols))
	},
		Entry("2010-04-04", "2010-04-04"),
	)

	DescribeTable("012_2Påskedag", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2. påskedag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. påskedag", hols))
	},
		Entry("2010-04-05", "2010-04-05"),
	)

	DescribeTable("013_KristiHimmelfartsdag", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Kristi Himmelfartsdag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Kristi Himmelfartsdag", hols))
	},
		Entry("2010-05-13", "2010-05-13"),
	)

	DescribeTable("014_1Pinsedag", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "1. pinsedag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "1. pinsedag", hols))
	},
		Entry("2010-05-23", "2010-05-23"),
	)

	DescribeTable("015_2Pinsedag", func(s string) {
		opts := holidays.Options{Regions: []string{"no"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "2. pinsedag")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "2. pinsedag", hols))
	},
		Entry("2010-05-24", "2010-05-24"),
	)

})
