// Code generated by gen-holidays from definitions/northamericainformal.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var northamericainformalRules = []definition.HolidayRule{
	{
		Name:    "Groundhog Day",
		Regions: []string{"us", "ca"},
		Month:   2,
		Mday:    2,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Valentine's Day",
		Regions: []string{"us", "ca"},
		Month:   2,
		Mday:    14,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "St. Patrick's Day",
		Regions: []string{"us", "ca"},
		Month:   3,
		Mday:    17,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "April Fool's Day",
		Regions: []string{"us", "ca"},
		Month:   4,
		Mday:    1,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Earth Day",
		Regions: []string{"us", "ca"},
		Month:   4,
		Mday:    22,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Mother's Day",
		Regions: []string{"us", "ca"},
		Month:   5,
		Wday:    0,
		Week:    2,
		Type:    definition.Informal,
	},
	{
		Name:    "Armed Forces Day",
		Regions: []string{"us"},
		Month:   5,
		Wday:    6,
		Week:    3,
		Type:    definition.Informal,
	},
	{
		Name:    "Father's Day",
		Regions: []string{"us", "ca"},
		Month:   6,
		Wday:    0,
		Week:    3,
		Type:    definition.Informal,
	},
	{
		Name:    "Halloween",
		Regions: []string{"us", "ca"},
		Month:   10,
		Mday:    31,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Day of the Dead",
		Regions: []string{"us", "ca"},
		Month:   11,
		Mday:    1,
		Wday:    -1,
		Type:    definition.Informal,
	},
	{
		Name:    "Day of the Dead",
		Regions: []string{"us", "ca"},
		Month:   11,
		Mday:    2,
		Wday:    -1,
		Type:    definition.Informal,
	},
}

var northamericainformalRegionNames = map[string]string{
	"ca": "Canada",
	"us": "United States",
}

func init() {
	engine.RegisterCountry("northamericainformal", northamericainformalRules)
	engine.RegisterRegionNames("northamericainformal", northamericainformalRegionNames)
}
