// Code generated by gen-holidays from definitions/nyse.yaml@v9.0.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("nyse", func() {
	DescribeTable("000_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2008-01-01", "2008-01-01"),
	)

	DescribeTable("001_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2017-01-02", "2017-01-02"),
		Entry("2012-01-02", "2012-01-02"),
		Entry("2011-01-01", "2011-01-01"),
		Entry("2006-01-02", "2006-01-02"),
	)

	DescribeTable("002_MartinLutherKingJrDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Martin Luther King, Jr. Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Martin Luther King, Jr. Day", hols))
	},
		Entry("2008-01-21", "2008-01-21"),
	)

	DescribeTable("003_PresidentsDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Presidents' Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Presidents' Day", hols))
	},
		Entry("2008-02-18", "2008-02-18"),
	)

	DescribeTable("004_GoodFriday", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Good Friday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols))
	},
		Entry("2008-03-21", "2008-03-21"),
	)

	DescribeTable("005_MemorialDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Memorial Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Memorial Day", hols))
	},
		Entry("2008-05-26", "2008-05-26"),
	)

	DescribeTable("006_IndependenceDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Independence Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independence Day", hols))
	},
		Entry("2008-07-04", "2008-07-04"),
	)

	DescribeTable("007_LaborDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Labor Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labor Day", hols))
	},
		Entry("2008-09-01", "2008-09-01"),
	)

	DescribeTable("008_Thanksgiving", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Thanksgiving")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Thanksgiving", hols))
	},
		Entry("2008-11-27", "2008-11-27"),
	)

	DescribeTable("009_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2008-12-25", "2008-12-25"),
	)

	DescribeTable("010_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2017-01-02", "2017-01-02"),
		Entry("2012-01-02", "2012-01-02"),
		Entry("2011-01-01", "2011-01-01"),
		Entry("2006-01-02", "2006-01-02"),
	)

	DescribeTable("011_JuneteenthNationalIndependenceDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Juneteenth National Independence Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Juneteenth National Independence Day", hols))
	},
		Entry("2022-06-20", "2022-06-20"),
		Entry("2023-06-19", "2023-06-19"),
		Entry("2024-06-19", "2024-06-19"),
		Entry("2027-06-18", "2027-06-18"),
	)

	DescribeTable("012_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"nyse"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2021-06-18", "2021-06-18"),
	)

})
