// Code generated by gen-holidays from definitions/nyse.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var nyseRules = []definition.HolidayRule{
	{
		Name:             "Good Friday",
		Regions:          []string{"nyse"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:     "New Year's Day",
		Regions:  []string{"nyse"},
		Month:    1,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_sunday",
	},
	{
		Name:    "Martin Luther King, Jr. Day",
		Regions: []string{"nyse"},
		Month:   1,
		Wday:    1,
		Week:    3,
	},
	{
		Name:    "Presidents' Day",
		Regions: []string{"nyse"},
		Month:   2,
		Wday:    1,
		Week:    3,
	},
	{
		Name:    "Memorial Day",
		Regions: []string{"nyse"},
		Month:   5,
		Wday:    1,
		Week:    -1,
	},
	{
		Name:     "Juneteenth National Independence Day",
		Regions:  []string{"nyse"},
		Month:    6,
		Mday:     19,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2022}},
		},
	},
	{
		Name:     "Independence Day",
		Regions:  []string{"nyse"},
		Month:    7,
		Mday:     4,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
	{
		Name:    "Labor Day",
		Regions: []string{"nyse"},
		Month:   9,
		Wday:    1,
		Week:    1,
	},
	{
		Name:    "Thanksgiving",
		Regions: []string{"nyse"},
		Month:   11,
		Wday:    4,
		Week:    4,
	},
	{
		Name:     "Christmas Day",
		Regions:  []string{"nyse"},
		Month:    12,
		Mday:     25,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
}

var nyseRegionNames = map[string]string{
	"nyse": "New York Stock Exchange",
}

func init() {
	engine.RegisterCountry("nyse", nyseRules)
	engine.RegisterRegionNames("nyse", nyseRegionNames)
}
