// Code generated by gen-holidays from definitions/nz.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("nz", func() {
	DescribeTable("000_SouthlandAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_sl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Southland Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Southland Anniversary Day", hols))
	},
		Entry("2024-04-02", "2024-04-02"),
	)

	DescribeTable("001_SouthlandAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_sl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Southland Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Southland Anniversary Day", hols))
	},
		Entry("2025-04-22", "2025-04-22"),
	)

	DescribeTable("002_HawkeSBayAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_hb"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Hawke's bay Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Hawke's bay Anniversary Day", hols))
	},
		Entry("2024-10-25", "2024-10-25"),
	)

	DescribeTable("003_HawkeSBayAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_hb"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Hawke's bay Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Hawke's bay Anniversary Day", hols))
	},
		Entry("2025-10-24", "2025-10-24"),
	)

	DescribeTable("004_NewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "New Year's Day", hols))
	},
		Entry("2007-01-01", "2007-01-01"),
	)

	DescribeTable("005_DayAfterNewYearSDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Day after New Year's Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Day after New Year's Day", hols))
	},
		Entry("2007-01-02", "2007-01-02"),
	)

	DescribeTable("006_WaitangiDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Waitangi Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Waitangi Day", hols))
	},
		Entry("2007-02-06", "2007-02-06"),
	)

	DescribeTable("007_GoodFriday", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Good Friday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols))
	},
		Entry("2007-04-06", "2007-04-06"),
	)

	DescribeTable("008_EasterMonday", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Easter Monday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Easter Monday", hols))
	},
		Entry("2007-04-09", "2007-04-09"),
	)

	DescribeTable("009_ANZACDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "ANZAC Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "ANZAC Day", hols))
	},
		Entry("2007-04-25", "2007-04-25"),
	)

	DescribeTable("010_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2007-12-25", "2007-12-25"),
	)

	DescribeTable("011_BoxingDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Boxing Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Boxing Day", hols))
	},
		Entry("2007-12-26", "2007-12-26"),
	)

	DescribeTable("012_ANZACDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "ANZAC Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "ANZAC Day", hols))
	},
		Entry("2015-04-25", "2015-04-25"),
	)

	DescribeTable("013_ANZACDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "ANZAC Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "ANZAC Day", hols))
	},
		Entry("2015-04-27", "2015-04-27"),
	)

	DescribeTable("014_ANZACDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "ANZAC Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "ANZAC Day", hols))
	},
		Entry("2016-04-25", "2016-04-25"),
	)

	DescribeTable("015_ANZACDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "ANZAC Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "ANZAC Day", hols))
	},
		Entry("2016-04-25", "2016-04-25"),
	)

	DescribeTable("016_WaitangiDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Waitangi Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Waitangi Day", hols))
	},
		Entry("2015-02-06", "2015-02-06"),
	)

	DescribeTable("017_WaitangiDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Waitangi Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Waitangi Day", hols))
	},
		Entry("2015-02-06", "2015-02-06"),
	)

	DescribeTable("018_WaitangiDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Waitangi Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Waitangi Day", hols))
	},
		Entry("2016-02-06", "2016-02-06"),
	)

	DescribeTable("019_WaitangiDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Waitangi Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Waitangi Day", hols))
	},
		Entry("2016-02-08", "2016-02-08"),
	)

	DescribeTable("020_NelsonAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_ne"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Nelson Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nelson Anniversary Day", hols))
	},
		Entry("2016-02-01", "2016-02-01"),
	)

	DescribeTable("021_NelsonAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_ne"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Nelson Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nelson Anniversary Day", hols))
	},
		Entry("2017-01-30", "2017-01-30"),
	)

	DescribeTable("022_NelsonAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_ne"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Nelson Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nelson Anniversary Day", hols))
	},
		Entry("2018-01-29", "2018-01-29"),
	)

	DescribeTable("023_NelsonAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_ne"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Nelson Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nelson Anniversary Day", hols))
	},
		Entry("2019-02-04", "2019-02-04"),
	)

	DescribeTable("024_TaranakiAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_ta"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Taranaki Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Taranaki Anniversary Day", hols))
	},
		Entry("2016-03-14", "2016-03-14"),
	)

	DescribeTable("025_TaranakiAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_ta"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Taranaki Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Taranaki Anniversary Day", hols))
	},
		Entry("2017-03-13", "2017-03-13"),
	)

	DescribeTable("026_TaranakiAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_ta"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Taranaki Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Taranaki Anniversary Day", hols))
	},
		Entry("2018-03-12", "2018-03-12"),
	)

	DescribeTable("027_TaranakiAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_ta"}, Observed: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Taranaki Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Taranaki Anniversary Day", hols))
	},
		Entry("2019-03-11", "2019-03-11"),
	)

	DescribeTable("028_Matariki", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Matariki")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Matariki", hols))
	},
		Entry("2022-06-24", "2022-06-24"),
	)

	DescribeTable("029_Matariki", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Matariki")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Matariki", hols))
	},
		Entry("2052-06-21", "2052-06-21"),
	)

	DescribeTable("030_QueenSBirthday", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Queen's Birthday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Queen's Birthday", hols))
	},
		Entry("2022-06-06", "2022-06-06"),
	)

	DescribeTable("031_KingSBirthday", func(s string) {
		opts := holidays.Options{Regions: []string{"nz"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "King's Birthday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "King's Birthday", hols))
	},
		Entry("2023-06-05", "2023-06-05"),
	)

	DescribeTable("032_CanterburyAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_ca"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Canterbury Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Canterbury Anniversary Day", hols))
	},
		Entry("2023-11-17", "2023-11-17"),
	)

	DescribeTable("033_CanterburyAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_ca"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Canterbury Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Canterbury Anniversary Day", hols))
	},
		Entry("2024-11-15", "2024-11-15"),
	)

	DescribeTable("034_CanterburyAnniversaryDay", func(s string) {
		opts := holidays.Options{Regions: []string{"nz_ca"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Canterbury Anniversary Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Canterbury Anniversary Day", hols))
	},
		Entry("2028-11-17", "2028-11-17"),
	)

})
