// Code generated by gen-holidays from definitions/ph.yaml@v9.0.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("ph", func() {
	DescribeTable("000_GoodFriday", func(s string) {
		opts := holidays.Options{Regions: []string{"ph"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Good Friday")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Good Friday", hols))
	},
		Entry("2015-04-03", "2015-04-03"),
	)

	DescribeTable("001_TheDayOfValor", func(s string) {
		opts := holidays.Options{Regions: []string{"ph"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "The Day of Valor")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "The Day of Valor", hols))
	},
		Entry("2015-04-09", "2015-04-09"),
	)

	DescribeTable("002_LaborDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ph"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Labor Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Labor Day", hols))
	},
		Entry("2015-05-01", "2015-05-01"),
	)

	DescribeTable("003_IndependenceDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ph"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Independence Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Independence Day", hols))
	},
		Entry("2015-06-12", "2015-06-12"),
	)

	DescribeTable("004_NinoyAquinoDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ph"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ninoy Aquino Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ninoy Aquino Day", hols))
	},
		Entry("2015-08-21", "2015-08-21"),
	)

	DescribeTable("005_NationalHeroesDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ph"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "National Heroes Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "National Heroes Day", hols))
	},
		Entry("2015-08-31", "2015-08-31"),
	)

	DescribeTable("006_NationalHeroesDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ph"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "National Heroes Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "National Heroes Day", hols))
	},
		Entry("2025-08-25", "2025-08-25"),
	)

	DescribeTable("007_BonifacioDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ph"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Bonifacio Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Bonifacio Day", hols))
	},
		Entry("2015-11-30", "2015-11-30"),
	)

	DescribeTable("008_ChristmasDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ph"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Christmas Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Christmas Day", hols))
	},
		Entry("2015-12-25", "2015-12-25"),
	)

	DescribeTable("009_RizalDay", func(s string) {
		opts := holidays.Options{Regions: []string{"ph"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Rizal Day")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Rizal Day", hols))
	},
		Entry("2015-12-30", "2015-12-30"),
	)

})
