// Code generated by gen-holidays from definitions/pl.yaml@v9.0.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("pl", func() {
	DescribeTable("000_NowyRok", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Nowy Rok")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nowy Rok", hols))
	},
		Entry("2011-01-01", "2011-01-01"),
	)

	DescribeTable("001_ŚwiętoPaństwoweŚwiętoPracy", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Święto Państwowe (Święto Pracy)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Święto Państwowe (Święto Pracy)", hols))
	},
		Entry("2011-05-01", "2011-05-01"),
	)

	DescribeTable("002_ŚwiętoNarodoweTrzeciegoMaja", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Święto Narodowe Trzeciego Maja")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Święto Narodowe Trzeciego Maja", hols))
	},
		Entry("2011-05-03", "2011-05-03"),
	)

	DescribeTable("003_WszystkichŚwiętych", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wszystkich Świętych")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wszystkich Świętych", hols))
	},
		Entry("2011-11-01", "2011-11-01"),
	)

	DescribeTable("004_NarodoweŚwiętoNiepodległości", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Narodowe Święto Niepodległości")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Narodowe Święto Niepodległości", hols))
	},
		Entry("2011-11-11", "2011-11-11"),
	)

	DescribeTable("005_PierwszyDzieńBożegoNarodzenia", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "pierwszy dzień Bożego Narodzenia")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "pierwszy dzień Bożego Narodzenia", hols))
	},
		Entry("2011-12-25", "2011-12-25"),
	)

	DescribeTable("006_DrugiDzieńBożegoNarodzenia", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "drugi dzień Bożego Narodzenia")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "drugi dzień Bożego Narodzenia", hols))
	},
		Entry("2011-12-26", "2011-12-26"),
	)

	DescribeTable("007_DzieńBabci", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dzień Babci")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dzień Babci", hols))
	},
		Entry("2011-01-21", "2011-01-21"),
	)

	DescribeTable("008_DzieńDziadka", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dzień Dziadka")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dzień Dziadka", hols))
	},
		Entry("2011-01-22", "2011-01-22"),
	)

	DescribeTable("009_OfiarowaniePańskieMatkiBoskiejGromnicznej", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ofiarowanie Pańskie (Matki Boskiej Gromnicznej)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ofiarowanie Pańskie (Matki Boskiej Gromnicznej)", hols))
	},
		Entry("2011-02-02", "2011-02-02"),
	)

	DescribeTable("010_DzieńZakochanychWalentynki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dzień Zakochanych (Walentynki)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dzień Zakochanych (Walentynki)", hols))
	},
		Entry("2011-02-14", "2011-02-14"),
	)

	DescribeTable("011_DzieńKobiet", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dzień Kobiet")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dzień Kobiet", hols))
	},
		Entry("2010-03-08", "2010-03-08"),
	)

	DescribeTable("012_DzieńMężczyzn", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dzień Mężczyzn")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dzień Mężczyzn", hols))
	},
		Entry("2011-03-10", "2011-03-10"),
	)

	DescribeTable("013_PrimaAprilis", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Prima Aprilis")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Prima Aprilis", hols))
	},
		Entry("2011-04-01", "2011-04-01"),
	)

	DescribeTable("014_MiędzynarodowyDzieńZiemi", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Międzynarodowy Dzień Ziemi")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Międzynarodowy Dzień Ziemi", hols))
	},
		Entry("2010-04-22", "2010-04-22"),
	)

	DescribeTable("015_DzieńFlagiRzeczpospolitejPolskiej", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dzień Flagi Rzeczpospolitej Polskiej")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dzień Flagi Rzeczpospolitej Polskiej", hols))
	},
		Entry("2011-05-02", "2011-05-02"),
	)

	DescribeTable("016_DzieńOjca", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dzień Ojca")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dzień Ojca", hols))
	},
		Entry("2010-06-23", "2010-06-23"),
	)

	DescribeTable("017_DzieńChłopaka", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dzień Chłopaka")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dzień Chłopaka", hols))
	},
		Entry("2011-09-30", "2011-09-30"),
	)

	DescribeTable("018_DzieńNauczycielaDzieńEdukacjiNarodowej", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dzień Nauczyciela (Dzień Edukacji Narodowej)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dzień Nauczyciela (Dzień Edukacji Narodowej)", hols))
	},
		Entry("2011-10-14", "2011-10-14"),
	)

	DescribeTable("019_DzieńZaduszny", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dzień Zaduszny")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dzień Zaduszny", hols))
	},
		Entry("2011-11-02", "2011-11-02"),
	)

	DescribeTable("020_Andrzejki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Andrzejki")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Andrzejki", hols))
	},
		Entry("2011-11-29", "2011-11-29"),
	)

	DescribeTable("021_BarbórkaDzieńGórnikaNaftowcaIGazownika", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Barbórka (Dzień Górnika, Naftowca i Gazownika)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Barbórka (Dzień Górnika, Naftowca i Gazownika)", hols))
	},
		Entry("2011-12-04", "2011-12-04"),
	)

	DescribeTable("022_Mikołajki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Mikołajki")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Mikołajki", hols))
	},
		Entry("2011-12-06", "2011-12-06"),
	)

	DescribeTable("023_WigiliaBożegoNarodzenia", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wigilia Bożego Narodzenia")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wigilia Bożego Narodzenia", hols))
	},
		Entry("2024-12-24", "2024-12-24"),
	)

	DescribeTable("024_WigiliaBożegoNarodzenia", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wigilia Bożego Narodzenia")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wigilia Bożego Narodzenia", hols))
	},
		Entry("2025-12-24", "2025-12-24"),
	)

	DescribeTable("025_Sylwester", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sylwester")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sylwester", hols))
	},
		Entry("2011-12-31", "2011-12-31"),
	)

	DescribeTable("026_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-01-21", "2011-01-21"),
	)

	DescribeTable("027_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-01-22", "2011-01-22"),
	)

	DescribeTable("028_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-02-02", "2011-02-02"),
	)

	DescribeTable("029_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-02-14", "2011-02-14"),
	)

	DescribeTable("030_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2010-03-08", "2010-03-08"),
	)

	DescribeTable("031_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-03-10", "2011-03-10"),
	)

	DescribeTable("032_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-04-01", "2011-04-01"),
	)

	DescribeTable("033_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2010-04-22", "2010-04-22"),
	)

	DescribeTable("034_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-05-02", "2011-05-02"),
	)

	DescribeTable("035_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2010-06-23", "2010-06-23"),
	)

	DescribeTable("036_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-09-30", "2011-09-30"),
	)

	DescribeTable("037_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-10-14", "2011-10-14"),
	)

	DescribeTable("038_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-11-02", "2011-11-02"),
	)

	DescribeTable("039_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-11-29", "2011-11-29"),
	)

	DescribeTable("040_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-12-04", "2011-12-04"),
	)

	DescribeTable("041_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-12-06", "2011-12-06"),
	)

	DescribeTable("042_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-12-24", "2011-12-24"),
	)

	DescribeTable("043_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2011-12-31", "2011-12-31"),
	)

	DescribeTable("044_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2008-01-06", "2008-01-06"),
	)

	DescribeTable("045_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2009-01-06", "2009-01-06"),
	)

	DescribeTable("046_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2010-01-06", "2010-01-06"),
	)

	DescribeTable("047_ObjawieniePańskieŚwiętoTrzechKróli", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Objawienie Pańskie (święto Trzech Króli)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Objawienie Pańskie (święto Trzech Króli)", hols))
	},
		Entry("2008-01-06", "2008-01-06"),
	)

	DescribeTable("048_ObjawieniePańskieŚwiętoTrzechKróli", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Objawienie Pańskie (święto Trzech Króli)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Objawienie Pańskie (święto Trzech Króli)", hols))
	},
		Entry("2009-01-06", "2009-01-06"),
	)

	DescribeTable("049_ObjawieniePańskieŚwiętoTrzechKróli", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Objawienie Pańskie (święto Trzech Króli)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Objawienie Pańskie (święto Trzech Króli)", hols))
	},
		Entry("2010-01-06", "2010-01-06"),
	)

	DescribeTable("050_ObjawieniePańskieŚwiętoTrzechKróli", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Objawienie Pańskie (święto Trzech Króli)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Objawienie Pańskie (święto Trzech Króli)", hols))
	},
		Entry("2011-01-06", "2011-01-06"),
	)

	DescribeTable("051_ObjawieniePańskieŚwiętoTrzechKróli", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Objawienie Pańskie (święto Trzech Króli)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Objawienie Pańskie (święto Trzech Króli)", hols))
	},
		Entry("2011-01-06", "2011-01-06"),
	)

	DescribeTable("052_ObjawieniePańskieŚwiętoTrzechKróli", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Objawienie Pańskie (święto Trzech Króli)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Objawienie Pańskie (święto Trzech Króli)", hols))
	},
		Entry("2012-01-06", "2012-01-06"),
	)

	DescribeTable("053_ObjawieniePańskieŚwiętoTrzechKróli", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Objawienie Pańskie (święto Trzech Króli)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Objawienie Pańskie (święto Trzech Króli)", hols))
	},
		Entry("2013-01-06", "2013-01-06"),
	)

	DescribeTable("054_TłustyCzwartek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Tłusty Czwartek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tłusty Czwartek", hols))
	},
		Entry("2008-01-31", "2008-01-31"),
	)

	DescribeTable("055_TłustyCzwartek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Tłusty Czwartek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tłusty Czwartek", hols))
	},
		Entry("2009-02-19", "2009-02-19"),
	)

	DescribeTable("056_TłustyCzwartek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Tłusty Czwartek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tłusty Czwartek", hols))
	},
		Entry("2010-02-11", "2010-02-11"),
	)

	DescribeTable("057_TłustyCzwartek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Tłusty Czwartek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tłusty Czwartek", hols))
	},
		Entry("2011-03-03", "2011-03-03"),
	)

	DescribeTable("058_TłustyCzwartek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Tłusty Czwartek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Tłusty Czwartek", hols))
	},
		Entry("2012-02-16", "2012-02-16"),
	)

	DescribeTable("059_Ostatki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ostatki")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ostatki", hols))
	},
		Entry("2008-02-05", "2008-02-05"),
	)

	DescribeTable("060_Ostatki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ostatki")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ostatki", hols))
	},
		Entry("2009-02-24", "2009-02-24"),
	)

	DescribeTable("061_Ostatki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ostatki")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ostatki", hols))
	},
		Entry("2010-02-16", "2010-02-16"),
	)

	DescribeTable("062_Ostatki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ostatki")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ostatki", hols))
	},
		Entry("2011-03-08", "2011-03-08"),
	)

	DescribeTable("063_Ostatki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ostatki")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ostatki", hols))
	},
		Entry("2012-02-21", "2012-02-21"),
	)

	DescribeTable("064_ŚrodaPopielcowa", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Środa Popielcowa")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Środa Popielcowa", hols))
	},
		Entry("2008-02-06", "2008-02-06"),
	)

	DescribeTable("065_ŚrodaPopielcowa", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Środa Popielcowa")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Środa Popielcowa", hols))
	},
		Entry("2009-02-25", "2009-02-25"),
	)

	DescribeTable("066_ŚrodaPopielcowa", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Środa Popielcowa")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Środa Popielcowa", hols))
	},
		Entry("2010-02-17", "2010-02-17"),
	)

	DescribeTable("067_ŚrodaPopielcowa", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Środa Popielcowa")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Środa Popielcowa", hols))
	},
		Entry("2011-03-09", "2011-03-09"),
	)

	DescribeTable("068_ŚrodaPopielcowa", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Środa Popielcowa")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Środa Popielcowa", hols))
	},
		Entry("2012-02-22", "2012-02-22"),
	)

	DescribeTable("069_NiedzielaPalmowa", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Niedziela Palmowa")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Niedziela Palmowa", hols))
	},
		Entry("2008-03-16", "2008-03-16"),
	)

	DescribeTable("070_NiedzielaPalmowa", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Niedziela Palmowa")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Niedziela Palmowa", hols))
	},
		Entry("2009-04-05", "2009-04-05"),
	)

	DescribeTable("071_NiedzielaPalmowa", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Niedziela Palmowa")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Niedziela Palmowa", hols))
	},
		Entry("2010-03-28", "2010-03-28"),
	)

	DescribeTable("072_NiedzielaPalmowa", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Niedziela Palmowa")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Niedziela Palmowa", hols))
	},
		Entry("2011-04-17", "2011-04-17"),
	)

	DescribeTable("073_NiedzielaPalmowa", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Niedziela Palmowa")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Niedziela Palmowa", hols))
	},
		Entry("2012-04-01", "2012-04-01"),
	)

	DescribeTable("074_WielkiCzwartek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielki Czwartek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielki Czwartek", hols))
	},
		Entry("2008-03-20", "2008-03-20"),
	)

	DescribeTable("075_WielkiCzwartek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielki Czwartek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielki Czwartek", hols))
	},
		Entry("2009-04-09", "2009-04-09"),
	)

	DescribeTable("076_WielkiCzwartek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielki Czwartek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielki Czwartek", hols))
	},
		Entry("2010-04-01", "2010-04-01"),
	)

	DescribeTable("077_WielkiCzwartek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielki Czwartek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielki Czwartek", hols))
	},
		Entry("2011-04-21", "2011-04-21"),
	)

	DescribeTable("078_WielkiCzwartek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielki Czwartek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielki Czwartek", hols))
	},
		Entry("2012-04-05", "2012-04-05"),
	)

	DescribeTable("079_WielkiPiątek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielki Piątek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielki Piątek", hols))
	},
		Entry("2008-03-21", "2008-03-21"),
	)

	DescribeTable("080_WielkiPiątek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielki Piątek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielki Piątek", hols))
	},
		Entry("2009-04-10", "2009-04-10"),
	)

	DescribeTable("081_WielkiPiątek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielki Piątek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielki Piątek", hols))
	},
		Entry("2010-04-02", "2010-04-02"),
	)

	DescribeTable("082_WielkiPiątek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielki Piątek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielki Piątek", hols))
	},
		Entry("2011-04-22", "2011-04-22"),
	)

	DescribeTable("083_WielkiPiątek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielki Piątek")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielki Piątek", hols))
	},
		Entry("2012-04-06", "2012-04-06"),
	)

	DescribeTable("084_WielkaSobota", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielka Sobota")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielka Sobota", hols))
	},
		Entry("2008-03-22", "2008-03-22"),
	)

	DescribeTable("085_WielkaSobota", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielka Sobota")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielka Sobota", hols))
	},
		Entry("2009-04-11", "2009-04-11"),
	)

	DescribeTable("086_WielkaSobota", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielka Sobota")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielka Sobota", hols))
	},
		Entry("2010-04-03", "2010-04-03"),
	)

	DescribeTable("087_WielkaSobota", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielka Sobota")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielka Sobota", hols))
	},
		Entry("2011-04-23", "2011-04-23"),
	)

	DescribeTable("088_WielkaSobota", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wielka Sobota")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wielka Sobota", hols))
	},
		Entry("2012-04-07", "2012-04-07"),
	)

	DescribeTable("089_NiedzielaWielkanocna", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Niedziela Wielkanocna")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Niedziela Wielkanocna", hols))
	},
		Entry("2008-03-23", "2008-03-23"),
	)

	DescribeTable("090_NiedzielaWielkanocna", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Niedziela Wielkanocna")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Niedziela Wielkanocna", hols))
	},
		Entry("2009-04-12", "2009-04-12"),
	)

	DescribeTable("091_NiedzielaWielkanocna", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Niedziela Wielkanocna")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Niedziela Wielkanocna", hols))
	},
		Entry("2010-04-04", "2010-04-04"),
	)

	DescribeTable("092_NiedzielaWielkanocna", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Niedziela Wielkanocna")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Niedziela Wielkanocna", hols))
	},
		Entry("2011-04-24", "2011-04-24"),
	)

	DescribeTable("093_NiedzielaWielkanocna", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Niedziela Wielkanocna")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Niedziela Wielkanocna", hols))
	},
		Entry("2012-04-08", "2012-04-08"),
	)

	DescribeTable("094_PoniedziałekWielkanocnyLanyPoniedziałek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Poniedziałek Wielkanocny (Lany Poniedziałek)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Poniedziałek Wielkanocny (Lany Poniedziałek)", hols))
	},
		Entry("2008-03-24", "2008-03-24"),
	)

	DescribeTable("095_PoniedziałekWielkanocnyLanyPoniedziałek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Poniedziałek Wielkanocny (Lany Poniedziałek)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Poniedziałek Wielkanocny (Lany Poniedziałek)", hols))
	},
		Entry("2009-04-13", "2009-04-13"),
	)

	DescribeTable("096_PoniedziałekWielkanocnyLanyPoniedziałek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Poniedziałek Wielkanocny (Lany Poniedziałek)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Poniedziałek Wielkanocny (Lany Poniedziałek)", hols))
	},
		Entry("2010-04-05", "2010-04-05"),
	)

	DescribeTable("097_PoniedziałekWielkanocnyLanyPoniedziałek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Poniedziałek Wielkanocny (Lany Poniedziałek)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Poniedziałek Wielkanocny (Lany Poniedziałek)", hols))
	},
		Entry("2011-04-25", "2011-04-25"),
	)

	DescribeTable("098_PoniedziałekWielkanocnyLanyPoniedziałek", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Poniedziałek Wielkanocny (Lany Poniedziałek)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Poniedziałek Wielkanocny (Lany Poniedziałek)", hols))
	},
		Entry("2012-04-09", "2012-04-09"),
	)

	DescribeTable("099_ZesłanieDuchaŚwiętegoZieloneŚwiątki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Zesłanie Ducha Świętego (Zielone Świątki)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Zesłanie Ducha Świętego (Zielone Świątki)", hols))
	},
		Entry("2008-05-11", "2008-05-11"),
	)

	DescribeTable("100_ZesłanieDuchaŚwiętegoZieloneŚwiątki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Zesłanie Ducha Świętego (Zielone Świątki)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Zesłanie Ducha Świętego (Zielone Świątki)", hols))
	},
		Entry("2009-05-31", "2009-05-31"),
	)

	DescribeTable("101_ZesłanieDuchaŚwiętegoZieloneŚwiątki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Zesłanie Ducha Świętego (Zielone Świątki)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Zesłanie Ducha Świętego (Zielone Świątki)", hols))
	},
		Entry("2010-05-23", "2010-05-23"),
	)

	DescribeTable("102_ZesłanieDuchaŚwiętegoZieloneŚwiątki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Zesłanie Ducha Świętego (Zielone Świątki)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Zesłanie Ducha Świętego (Zielone Świątki)", hols))
	},
		Entry("2011-06-12", "2011-06-12"),
	)

	DescribeTable("103_ZesłanieDuchaŚwiętegoZieloneŚwiątki", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Zesłanie Ducha Świętego (Zielone Świątki)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Zesłanie Ducha Świętego (Zielone Świątki)", hols))
	},
		Entry("2012-05-27", "2012-05-27"),
	)

	DescribeTable("104_UroczystośćNajświętszegoCiałaIKrwiPańskiejBożeCiało", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Uroczystość Najświętszego Ciała i Krwi Pańskiej (Boże Ciało)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Uroczystość Najświętszego Ciała i Krwi Pańskiej (Boże Ciało)", hols))
	},
		Entry("2008-05-22", "2008-05-22"),
	)

	DescribeTable("105_UroczystośćNajświętszegoCiałaIKrwiPańskiejBożeCiało", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Uroczystość Najświętszego Ciała i Krwi Pańskiej (Boże Ciało)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Uroczystość Najświętszego Ciała i Krwi Pańskiej (Boże Ciało)", hols))
	},
		Entry("2009-06-11", "2009-06-11"),
	)

	DescribeTable("106_UroczystośćNajświętszegoCiałaIKrwiPańskiejBożeCiało", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Uroczystość Najświętszego Ciała i Krwi Pańskiej (Boże Ciało)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Uroczystość Najświętszego Ciała i Krwi Pańskiej (Boże Ciało)", hols))
	},
		Entry("2010-06-03", "2010-06-03"),
	)

	DescribeTable("107_UroczystośćNajświętszegoCiałaIKrwiPańskiejBożeCiało", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Uroczystość Najświętszego Ciała i Krwi Pańskiej (Boże Ciało)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Uroczystość Najświętszego Ciała i Krwi Pańskiej (Boże Ciało)", hols))
	},
		Entry("2011-06-23", "2011-06-23"),
	)

	DescribeTable("108_UroczystośćNajświętszegoCiałaIKrwiPańskiejBożeCiało", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Uroczystość Najświętszego Ciała i Krwi Pańskiej (Boże Ciało)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Uroczystość Najświętszego Ciała i Krwi Pańskiej (Boże Ciało)", hols))
	},
		Entry("2012-06-07", "2012-06-07"),
	)

	DescribeTable("109_WniebowzięcieNajświętszejMaryiPanny", func(s string) {
		opts := holidays.Options{Regions: []string{"pl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Wniebowzięcie Najświętszej Maryi Panny")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Wniebowzięcie Najświętszej Maryi Panny", hols))
	},
		Entry("2011-08-15", "2011-08-15"),
	)

})
