// Code generated by gen-holidays from definitions/pt.yaml@v9.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var ptRules = []definition.HolidayRule{
	{
		Name:             "Carnaval",
		Regions:          []string{"pt"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -47,
		Type:             definition.Informal,
	},
	{
		Name:             "Sexta-feira Santa",
		Regions:          []string{"pt"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:         "Páscoa",
		Regions:      []string{"pt"},
		Month:        0,
		Wday:         -1,
		Function:     "easter",
		FunctionArgs: []string{"year"},
	},
	{
		Name:             "Corpo de Deus",
		Regions:          []string{"pt"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 60,
	},
	{
		Name:    "Ano Novo",
		Regions: []string{"pt"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Dia da Liberdade",
		Regions: []string{"pt"},
		Month:   4,
		Mday:    25,
		Wday:    -1,
	},
	{
		Name:    "Dia do Trabalhador",
		Regions: []string{"pt"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Dia de Portugal",
		Regions: []string{"pt"},
		Month:   6,
		Mday:    10,
		Wday:    -1,
	},
	{
		Name:    "Dia de Santo António",
		Regions: []string{"pt_li"},
		Month:   6,
		Mday:    13,
		Wday:    -1,
	},
	{
		Name:    "Dia de São João",
		Regions: []string{"pt_po"},
		Month:   6,
		Mday:    24,
		Wday:    -1,
	},
	{
		Name:    "Assunção de Nossa Senhora",
		Regions: []string{"pt"},
		Month:   8,
		Mday:    15,
		Wday:    -1,
	},
	{
		Name:    "Dia da República",
		Regions: []string{"pt"},
		Month:   10,
		Mday:    5,
		Wday:    -1,
	},
	{
		Name:    "Dia de Todos-os-Santos",
		Regions: []string{"pt"},
		Month:   11,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Restauração da Independência",
		Regions: []string{"pt"},
		Month:   12,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Imaculada Conceição",
		Regions: []string{"pt"},
		Month:   12,
		Mday:    8,
		Wday:    -1,
	},
	{
		Name:    "Natal",
		Regions: []string{"pt"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
}

var ptRegionNames = map[string]string{
	"pt":    "Portugal",
	"pt_li": "Lisbon",
	"pt_po": "Porto",
}

func init() {
	engine.RegisterCountry("pt", ptRules)
	engine.RegisterRegionNames("pt", ptRegionNames)
}
