// Code generated by gen-holidays from definitions/ro.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("ro", func() {
	DescribeTable("000_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2017-04-14", "2017-04-14"),
	)

	DescribeTable("001_PașteleVinereaMare", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Paștele - Vinerea Mare")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Paștele - Vinerea Mare", hols))
	},
		Entry("2018-04-06", "2018-04-06"),
	)

	DescribeTable("002_PașteleVinereaMare", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Paștele - Vinerea Mare")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Paștele - Vinerea Mare", hols))
	},
		Entry("2019-04-26", "2019-04-26"),
	)

	DescribeTable("003_PașteleDuminică", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Paștele - duminică")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Paștele - duminică", hols))
	},
		Entry("1961-04-09", "1961-04-09"),
	)

	DescribeTable("004_PașteleLuni", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Paștele - luni")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Paștele - luni", hols))
	},
		Entry("1961-04-10", "1961-04-10"),
	)

	DescribeTable("005_PașteleDuminică", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Paștele - duminică")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Paștele - duminică", hols))
	},
		Entry("2013-05-05", "2013-05-05"),
	)

	DescribeTable("006_PașteleLuni", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Paștele - luni")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Paștele - luni", hols))
	},
		Entry("2013-05-06", "2013-05-06"),
	)

	DescribeTable("007_PașteleDuminică", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Paștele - duminică")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Paștele - duminică", hols))
	},
		Entry("2027-05-02", "2027-05-02"),
	)

	DescribeTable("008_PașteleLuni", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Paștele - luni")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Paștele - luni", hols))
	},
		Entry("2027-05-03", "2027-05-03"),
	)

	DescribeTable("009_Rusaliile51", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Rusaliile - 51")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Rusaliile - 51", hols))
	},
		Entry("2012-06-04", "2012-06-04"),
	)

	DescribeTable("010_Rusaliile50", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Rusaliile - 50")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Rusaliile - 50", hols))
	},
		Entry("2013-06-23", "2013-06-23"),
	)

	DescribeTable("011_Rusaliile51", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Rusaliile - 51")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Rusaliile - 51", hols))
	},
		Entry("2013-06-24", "2013-06-24"),
	)

	DescribeTable("012_Rusaliile50", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Rusaliile - 50")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Rusaliile - 50", hols))
	},
		Entry("1986-06-22", "1986-06-22"),
	)

	DescribeTable("013_Rusaliile51", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Rusaliile - 51")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Rusaliile - 51", hols))
	},
		Entry("1986-06-23", "1986-06-23"),
	)

	DescribeTable("014_AnulNou", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Anul nou")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Anul nou", hols))
	},
		Entry("2009-01-01", "2009-01-01"),
	)

	DescribeTable("015_AnulNou", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Anul nou")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Anul nou", hols))
	},
		Entry("2014-01-02", "2014-01-02"),
	)

	DescribeTable("016_UnireaPrincipatelorRomâne", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Unirea Principatelor Române")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Unirea Principatelor Române", hols))
	},
		Entry("2017-01-24", "2017-01-24"),
	)

	DescribeTable("017_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2016-01-24", "2016-01-24"),
	)

	DescribeTable("018_ZiuaMuncii", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ziua muncii")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ziua muncii", hols))
	},
		Entry("2009-05-01", "2009-05-01"),
	)

	DescribeTable("019_ZiuaCopilului", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ziua Copilului")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ziua Copilului", hols))
	},
		Entry("2017-06-01", "2017-06-01"),
	)

	DescribeTable("020_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2016-06-01", "2016-06-01"),
	)

	DescribeTable("021_AdormireaMaiciiDomnului", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Adormirea Maicii Domnului")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Adormirea Maicii Domnului", hols))
	},
		Entry("2012-08-15", "2012-08-15"),
	)

	DescribeTable("022_SfântulApostolAndrei", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sfântul Apostol Andrei")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sfântul Apostol Andrei", hols))
	},
		Entry("2013-11-30", "2013-11-30"),
	)

	DescribeTable("023_ZiuaNațională", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ziua Națională")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ziua Națională", hols))
	},
		Entry("2013-12-01", "2013-12-01"),
	)

	DescribeTable("024_SărbătoareaNașteriiDomnului", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sărbătoarea Nașterii Domnului")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sărbătoarea Nașterii Domnului", hols))
	},
		Entry("2013-12-25", "2013-12-25"),
	)

	DescribeTable("025_SărbătoareaNașteriiDomnului", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Sărbătoarea Nașterii Domnului")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Sărbătoarea Nașterii Domnului", hols))
	},
		Entry("2013-12-26", "2013-12-26"),
	)

	DescribeTable("026_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2013-07-23", "2013-07-23"),
	)

	DescribeTable("027_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2023-01-06", "2023-01-06"),
	)

	DescribeTable("028_Negative", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hols).To(BeEmpty(), fmt.Sprintf("On(%s, %v): expected no holiday, got %v", s, opts.Regions, hols))
	},
		Entry("2023-01-07", "2023-01-07"),
	)

	DescribeTable("029_BotezulDomnuluiBoboteaza", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Botezul Domnului - Boboteaza")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Botezul Domnului - Boboteaza", hols))
	},
		Entry("2024-01-06", "2024-01-06"),
	)

	DescribeTable("030_SoborulSfântuluiProrocIoanBotezătorul", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Soborul Sfântului Proroc Ioan Botezătorul")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Soborul Sfântului Proroc Ioan Botezătorul", hols))
	},
		Entry("2024-01-07", "2024-01-07"),
	)

	DescribeTable("031_BotezulDomnuluiBoboteaza", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Botezul Domnului - Boboteaza")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Botezul Domnului - Boboteaza", hols))
	},
		Entry("2025-01-06", "2025-01-06"),
	)

	DescribeTable("032_SoborulSfântuluiProrocIoanBotezătorul", func(s string) {
		opts := holidays.Options{Regions: []string{"ro"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Soborul Sfântului Proroc Ioan Botezătorul")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Soborul Sfântului Proroc Ioan Botezătorul", hols))
	},
		Entry("2025-01-07", "2025-01-07"),
	)

})
