// Code generated by gen-holidays from definitions/rs_cyrl.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("rs_cyrl", func() {
	DescribeTable("000_НоваГодина", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Нова Година")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Нова Година", hols))
	},
		Entry("2017-1-1", "2017-1-1"),
		Entry("2017-1-2", "2017-1-2"),
	)

	DescribeTable("001_Божић", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Божић")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Божић", hols))
	},
		Entry("2017-1-7", "2017-1-7"),
	)

	DescribeTable("002_СветиСаваСавиндан", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Свети Сава (Савиндан)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Свети Сава (Савиндан)", hols))
	},
		Entry("2017-1-27", "2017-1-27"),
	)

	DescribeTable("003_ДанДржавностиСрбије", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Дан државности Србије")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Дан државности Србије", hols))
	},
		Entry("2017-2-15", "2017-2-15"),
		Entry("2017-2-16", "2017-2-16"),
	)

	DescribeTable("004_ПразникРада", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Празник рада")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Празник рада", hols))
	},
		Entry("2017-5-1", "2017-5-1"),
		Entry("2017-5-2", "2017-5-2"),
	)

	DescribeTable("005_ДанПобедеНадФашизмом", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Дан победе над фашизмом")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Дан победе над фашизмом", hols))
	},
		Entry("2017-5-9", "2017-5-9"),
	)

	DescribeTable("006_Видовдан", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Видовдан")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Видовдан", hols))
	},
		Entry("2017-6-28", "2017-6-28"),
	)

	DescribeTable("007_ДанПримирја", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Дан примирја")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Дан примирја", hols))
	},
		Entry("2017-11-11", "2017-11-11"),
	)

	DescribeTable("008_ВеликиПетак", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Велики петак")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Велики петак", hols))
	},
		Entry("2017-4-14", "2017-4-14"),
		Entry("2018-4-6", "2018-4-6"),
		Entry("2019-4-26", "2019-4-26"),
	)

	DescribeTable("009_ВеликаСубота", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Велика Субота")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Велика Субота", hols))
	},
		Entry("2017-4-15", "2017-4-15"),
		Entry("2018-4-7", "2018-4-7"),
		Entry("2019-4-27", "2019-4-27"),
	)

	DescribeTable("010_Васкрс", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Васкрс")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Васкрс", hols))
	},
		Entry("2017-4-16", "2017-4-16"),
		Entry("2018-4-8", "2018-4-8"),
		Entry("2019-4-28", "2019-4-28"),
	)

	DescribeTable("011_ВаскрсниПонедељак", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_cyrl"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Васкрсни понедељак")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Васкрсни понедељак", hols))
	},
		Entry("2017-4-17", "2017-4-17"),
		Entry("2018-4-9", "2018-4-9"),
		Entry("2019-4-29", "2019-4-29"),
	)

})
