// Code generated by gen-holidays from definitions/rs_la.yaml@v9.0.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("rs_la", func() {
	DescribeTable("000_NovaGodina", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Nova Godina")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Nova Godina", hols))
	},
		Entry("2017-1-1", "2017-1-1"),
		Entry("2017-1-2", "2017-1-2"),
	)

	DescribeTable("001_Božić", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Božić")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Božić", hols))
	},
		Entry("2017-1-7", "2017-1-7"),
	)

	DescribeTable("002_DanSvetogSave", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dan Svetog Save")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dan Svetog Save", hols))
	},
		Entry("2017-1-27", "2017-1-27"),
	)

	DescribeTable("003_DanDržavnostiSrbije", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dan državnosti Srbije")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dan državnosti Srbije", hols))
	},
		Entry("2017-2-15", "2017-2-15"),
		Entry("2017-2-16", "2017-2-16"),
	)

	DescribeTable("004_PraznikRada", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Praznik rada")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Praznik rada", hols))
	},
		Entry("2017-5-1", "2017-5-1"),
		Entry("2017-5-2", "2017-5-2"),
	)

	DescribeTable("005_DanPobede", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dan pobede")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dan pobede", hols))
	},
		Entry("2017-5-9", "2017-5-9"),
	)

	DescribeTable("006_Vidovdan", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Vidovdan")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Vidovdan", hols))
	},
		Entry("2017-6-28", "2017-6-28"),
	)

	DescribeTable("007_DanPrimirja", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Dan primirja")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Dan primirja", hols))
	},
		Entry("2017-11-11", "2017-11-11"),
	)

	DescribeTable("008_VelikiPetak", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Veliki Petak")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Veliki Petak", hols))
	},
		Entry("2017-4-14", "2017-4-14"),
		Entry("2018-4-6", "2018-4-6"),
		Entry("2019-4-26", "2019-4-26"),
	)

	DescribeTable("009_VelikaSubota", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Velika Subota")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Velika Subota", hols))
	},
		Entry("2017-4-15", "2017-4-15"),
		Entry("2018-4-7", "2018-4-7"),
		Entry("2019-4-27", "2019-4-27"),
	)

	DescribeTable("010_Uskrs", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Uskrs")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Uskrs", hols))
	},
		Entry("2017-4-16", "2017-4-16"),
		Entry("2018-4-8", "2018-4-8"),
		Entry("2019-4-28", "2019-4-28"),
	)

	DescribeTable("011_VaskrsniPonedeljak", func(s string) {
		opts := holidays.Options{Regions: []string{"rs_la"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Vaskrsni ponedeljak")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Vaskrsni ponedeljak", hols))
	},
		Entry("2017-4-17", "2017-4-17"),
		Entry("2018-4-9", "2018-4-9"),
		Entry("2019-4-29", "2019-4-29"),
	)

})
