// Code generated by gen-holidays from definitions/ru.yaml@v9.0.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("ru", func() {
	DescribeTable("000_НовыйГод", func(s string) {
		opts := holidays.Options{Regions: []string{"ru"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Новый год")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Новый год", hols))
	},
		Entry("2017-1-1", "2017-1-1"),
	)

	DescribeTable("001_НовогоднийПраздник", func(s string) {
		opts := holidays.Options{Regions: []string{"ru"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Новогодний праздник")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Новогодний праздник", hols))
	},
		Entry("2017-1-2", "2017-1-2"),
		Entry("2017-1-3", "2017-1-3"),
		Entry("2017-1-4", "2017-1-4"),
		Entry("2017-1-5", "2017-1-5"),
	)

	DescribeTable("002_РождествоХристово", func(s string) {
		opts := holidays.Options{Regions: []string{"ru"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Рождество Христово")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Рождество Христово", hols))
	},
		Entry("2017-1-7", "2017-1-7"),
	)

	DescribeTable("003_ДеньЗащитникаОтечества", func(s string) {
		opts := holidays.Options{Regions: []string{"ru"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "День защитника Отечества")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "День защитника Отечества", hols))
	},
		Entry("2017-2-23", "2017-2-23"),
	)

	DescribeTable("004_МеждународныйЖенскийДень", func(s string) {
		opts := holidays.Options{Regions: []string{"ru"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Международный женский день")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Международный женский день", hols))
	},
		Entry("2017-3-8", "2017-3-8"),
	)

	DescribeTable("005_ПраздникВесныИТруда", func(s string) {
		opts := holidays.Options{Regions: []string{"ru"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Праздник Весны и Труда")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Праздник Весны и Труда", hols))
	},
		Entry("2017-5-1", "2017-5-1"),
	)

	DescribeTable("006_ДеньПобеды", func(s string) {
		opts := holidays.Options{Regions: []string{"ru"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "День Победы")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "День Победы", hols))
	},
		Entry("2017-5-9", "2017-5-9"),
	)

	DescribeTable("007_ДеньРоссии", func(s string) {
		opts := holidays.Options{Regions: []string{"ru"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "День России")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "День России", hols))
	},
		Entry("2017-6-12", "2017-6-12"),
	)

	DescribeTable("008_ДеньГосударственногоФлагаРоссийскойФедерации", func(s string) {
		opts := holidays.Options{Regions: []string{"ru"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "День Государственного флага Российской Федерации")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "День Государственного флага Российской Федерации", hols))
	},
		Entry("2017-8-22", "2017-8-22"),
	)

	DescribeTable("009_ДеньНародногоЕдинства", func(s string) {
		opts := holidays.Options{Regions: []string{"ru"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "День народного единства")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "День народного единства", hols))
	},
		Entry("2017-11-4", "2017-11-4"),
	)

})
