// Code generated by gen-holidays from definitions/th.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("th", func() {
	DescribeTable("000_วนขนปใหม", func(s string) {
		opts := holidays.Options{Regions: []string{"th"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "วันขึ้นปีใหม่")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันขึ้นปีใหม่", hols))
	},
		Entry("2019-01-01", "2019-01-01"),
	)

	DescribeTable("001_วนจกร", func(s string) {
		opts := holidays.Options{Regions: []string{"th"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "วันจักรี")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันจักรี", hols))
	},
		Entry("2019-04-06", "2019-04-06"),
	)

	DescribeTable("002_วนสงกรานต", func(s string) {
		opts := holidays.Options{Regions: []string{"th"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "วันสงกรานต์")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันสงกรานต์", hols))
	},
		Entry("2019-04-13", "2019-04-13"),
		Entry("2019-04-14", "2019-04-14"),
		Entry("2019-04-15", "2019-04-15"),
	)

	DescribeTable("003_วนเฉลมพระชนมพรรษาสมเดจพระเจาอยหวมหาวชราลงกรณบดนทรเทพยวรางกร", func(s string) {
		opts := holidays.Options{Regions: []string{"th"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "วันเฉลิมพระชนมพรรษาสมเด็จพระเจ้าอยู่หัวมหาวชิราลงกรณ บดินทรเทพยวรางกูร")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันเฉลิมพระชนมพรรษาสมเด็จพระเจ้าอยู่หัวมหาวชิราลงกรณ บดินทรเทพยวรางกูร", hols))
	},
		Entry("2019-07-28", "2019-07-28"),
	)

	DescribeTable("004_วนเฉลมพระชนมพรรษาสมเดจพระนางเจาสรกตพระบรมราชนนาถในรชกาลท๙", func(s string) {
		opts := holidays.Options{Regions: []string{"th"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "วันเฉลิมพระชนมพรรษาสมเด็จพระนางเจ้าสิริกิติ์ พระบรมราชินีนาถในรัชกาลที่ ๙")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันเฉลิมพระชนมพรรษาสมเด็จพระนางเจ้าสิริกิติ์ พระบรมราชินีนาถในรัชกาลที่ ๙", hols))
	},
		Entry("2007-08-12", "2007-08-12"),
	)

	DescribeTable("005_วนคลายวนสวรรคตพระบาทสมเดจพระปรมนทรมหาภมพลอดลยเดชบรมนาถบพตร", func(s string) {
		opts := holidays.Options{Regions: []string{"th"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "วันคล้ายวันสวรรคตพระบาทสมเด็จพระปรมินทรมหาภูมิพลอดุลยเดช บรมนาถบพิตร")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันคล้ายวันสวรรคตพระบาทสมเด็จพระปรมินทรมหาภูมิพลอดุลยเดช บรมนาถบพิตร", hols))
	},
		Entry("2019-10-13", "2019-10-13"),
	)

	DescribeTable("006_วนปยมหาราช", func(s string) {
		opts := holidays.Options{Regions: []string{"th"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "วันปิยมหาราช")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันปิยมหาราช", hols))
	},
		Entry("2019-10-23", "2019-10-23"),
	)

	DescribeTable("007_วนคลายวนเฉลมพระชนมพรรษาพระบาทสมเดจพระปรมนทรมหาภมพลอดลยเดชบรมนาถบพตร", func(s string) {
		opts := holidays.Options{Regions: []string{"th"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "วันคล้ายวันเฉลิมพระชนมพรรษาพระบาทสมเด็จพระปรมินทรมหาภูมิพลอดุลยเดช บรมนาถบพิตร")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันคล้ายวันเฉลิมพระชนมพรรษาพระบาทสมเด็จพระปรมินทรมหาภูมิพลอดุลยเดช บรมนาถบพิตร", hols))
	},
		Entry("2019-12-05", "2019-12-05"),
	)

	DescribeTable("008_วนรฐธรรมนญ", func(s string) {
		opts := holidays.Options{Regions: []string{"th"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "วันรัฐธรรมนูญ")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันรัฐธรรมนูญ", hols))
	},
		Entry("2019-12-10", "2019-12-10"),
	)

	DescribeTable("009_วนสนป", func(s string) {
		opts := holidays.Options{Regions: []string{"th"}, Informal: true}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "วันสิ้นปี")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "วันสิ้นปี", hols))
	},
		Entry("2019-12-31", "2019-12-31"),
	)

})
