// Code generated by gen-holidays from definitions/tn.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("tn", func() {
	DescribeTable("000_JourDeLAn", func(s string) {
		opts := holidays.Options{Regions: []string{"tn"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Jour de l'an")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Jour de l'an", hols))
	},
		Entry("2016-01-01", "2016-01-01"),
	)

	DescribeTable("001_FêteDeLaRévolutionEtDeLaJeunesse", func(s string) {
		opts := holidays.Options{Regions: []string{"tn"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fête de la Révolution et de la Jeunesse")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête de la Révolution et de la Jeunesse", hols))
	},
		Entry("2016-01-14", "2016-01-14"),
	)

	DescribeTable("002_FêteDeLIndépendance", func(s string) {
		opts := holidays.Options{Regions: []string{"tn"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fête de l'Indépendance")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête de l'Indépendance", hols))
	},
		Entry("2016-03-20", "2016-03-20"),
	)

	DescribeTable("003_JournéeDesMartyrs", func(s string) {
		opts := holidays.Options{Regions: []string{"tn"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Journée des Martyrs")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Journée des Martyrs", hols))
	},
		Entry("2016-04-09", "2016-04-09"),
	)

	DescribeTable("004_FêteDuTravail", func(s string) {
		opts := holidays.Options{Regions: []string{"tn"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fête du travail")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête du travail", hols))
	},
		Entry("2016-05-01", "2016-05-01"),
	)

	DescribeTable("005_FêteDeLaRépublique", func(s string) {
		opts := holidays.Options{Regions: []string{"tn"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fête de la République")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête de la République", hols))
	},
		Entry("2016-07-25", "2016-07-25"),
	)

	DescribeTable("006_FêteDeLaFemmeEtDeLaFamille", func(s string) {
		opts := holidays.Options{Regions: []string{"tn"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fête de la Femme et de la Famille")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête de la Femme et de la Famille", hols))
	},
		Entry("2016-08-13", "2016-08-13"),
	)

	DescribeTable("007_FêteDeLÉvacuation", func(s string) {
		opts := holidays.Options{Regions: []string{"tn"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Fête de l'Évacuation")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Fête de l'Évacuation", hols))
	},
		Entry("2016-10-15", "2016-10-15"),
	)

})
