// Code generated by gen-holidays from definitions/tr.yaml@v9.1.0. DO NOT EDIT.

package definitions_test

import (
	"fmt"

	holidays "github.com/holidays/go-holidays"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("tr", func() {
	DescribeTable("000_Yılbaşı", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Yılbaşı")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Yılbaşı", hols))
	},
		Entry("2017-1-1", "2017-1-1"),
	)

	DescribeTable("001_UlusalEgemenlikVeÇocukBayramı", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ulusal Egemenlik ve Çocuk Bayramı")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ulusal Egemenlik ve Çocuk Bayramı", hols))
	},
		Entry("2017-4-23", "2017-4-23"),
	)

	DescribeTable("002_EmekVeDayanışmaGünü", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Emek ve Dayanışma Günü")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Emek ve Dayanışma Günü", hols))
	},
		Entry("2017-5-1", "2017-5-1"),
	)

	DescribeTable("003_AtatürkÜAnmaGençlikVeSporBayramı", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Atatürk'ü Anma Gençlik ve Spor Bayramı")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Atatürk'ü Anma Gençlik ve Spor Bayramı", hols))
	},
		Entry("2017-5-19", "2017-5-19"),
	)

	DescribeTable("004_ZaferBayramı", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Zafer Bayramı")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Zafer Bayramı", hols))
	},
		Entry("2017-8-30", "2017-8-30"),
	)

	DescribeTable("005_CumhuriyetBayramı", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Cumhuriyet Bayramı")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Cumhuriyet Bayramı", hols))
	},
		Entry("2017-10-29", "2017-10-29"),
	)

	DescribeTable("006_RamazanBayramı", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ramazan Bayramı")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ramazan Bayramı", hols))
	},
		Entry("2017-6-25", "2017-6-25"),
		Entry("2018-6-15", "2018-6-15"),
		Entry("2019-6-4", "2019-6-4"),
		Entry("2020-5-24", "2020-5-24"),
		Entry("2021-5-13", "2021-5-13"),
		Entry("2022-5-2", "2022-5-2"),
		Entry("2023-4-21", "2023-4-21"),
		Entry("2024-4-10", "2024-4-10"),
		Entry("2025-3-30", "2025-3-30"),
		Entry("2026-3-20", "2026-3-20"),
		Entry("2027-3-9", "2027-3-9"),
		Entry("2028-2-26", "2028-2-26"),
		Entry("2029-2-15", "2029-2-15"),
		Entry("2030-2-4", "2030-2-4"),
		Entry("2031-1-25", "2031-1-25"),
		Entry("2032-1-14", "2032-1-14"),
	)

	DescribeTable("007_RamazanBayramıIkinciTatil", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ramazan Bayramı (ikinci tatil)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ramazan Bayramı (ikinci tatil)", hols))
	},
		Entry("2017-6-26", "2017-6-26"),
		Entry("2018-6-16", "2018-6-16"),
		Entry("2019-6-5", "2019-6-5"),
		Entry("2020-5-25", "2020-5-25"),
		Entry("2021-5-14", "2021-5-14"),
		Entry("2022-5-3", "2022-5-3"),
		Entry("2023-4-22", "2023-4-22"),
		Entry("2024-4-11", "2024-4-11"),
		Entry("2025-3-31", "2025-3-31"),
		Entry("2026-3-21", "2026-3-21"),
		Entry("2027-3-10", "2027-3-10"),
		Entry("2028-2-27", "2028-2-27"),
		Entry("2029-2-16", "2029-2-16"),
		Entry("2030-2-5", "2030-2-5"),
		Entry("2031-1-26", "2031-1-26"),
		Entry("2032-1-15", "2032-1-15"),
	)

	DescribeTable("008_RamazanBayramıÜçüncüTatil", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Ramazan Bayramı (üçüncü tatil)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Ramazan Bayramı (üçüncü tatil)", hols))
	},
		Entry("2017-6-27", "2017-6-27"),
		Entry("2018-6-17", "2018-6-17"),
		Entry("2019-6-6", "2019-6-6"),
		Entry("2020-5-26", "2020-5-26"),
		Entry("2021-5-15", "2021-5-15"),
		Entry("2022-5-4", "2022-5-4"),
		Entry("2023-4-23", "2023-4-23"),
		Entry("2024-4-12", "2024-4-12"),
		Entry("2025-4-1", "2025-4-1"),
		Entry("2026-3-22", "2026-3-22"),
		Entry("2027-3-11", "2027-3-11"),
		Entry("2028-2-28", "2028-2-28"),
		Entry("2029-2-17", "2029-2-17"),
		Entry("2030-2-6", "2030-2-6"),
		Entry("2031-1-27", "2031-1-27"),
		Entry("2032-1-16", "2032-1-16"),
	)

	DescribeTable("009_DemokrasiVeMilliBirlikGünü", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Demokrasi ve Milli Birlik Günü")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Demokrasi ve Milli Birlik Günü", hols))
	},
		Entry("2017-7-15", "2017-7-15"),
	)

	DescribeTable("010_KurbanBayramı", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Kurban Bayramı")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Kurban Bayramı", hols))
	},
		Entry("2017-9-1", "2017-9-1"),
		Entry("2018-8-21", "2018-8-21"),
		Entry("2019-8-11", "2019-8-11"),
		Entry("2020-7-31", "2020-7-31"),
		Entry("2021-7-20", "2021-7-20"),
		Entry("2022-7-9", "2022-7-9"),
		Entry("2023-6-28", "2023-6-28"),
		Entry("2024-6-16", "2024-6-16"),
		Entry("2025-6-6", "2025-6-6"),
		Entry("2026-5-27", "2026-5-27"),
		Entry("2027-5-16", "2027-5-16"),
		Entry("2028-5-5", "2028-5-5"),
		Entry("2029-4-24", "2029-4-24"),
		Entry("2030-4-13", "2030-4-13"),
		Entry("2031-4-3", "2031-4-3"),
		Entry("2032-3-22", "2032-3-22"),
	)

	DescribeTable("011_KurbanBayramıIkinciTatil", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Kurban Bayramı (ikinci tatil)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Kurban Bayramı (ikinci tatil)", hols))
	},
		Entry("2017-9-2", "2017-9-2"),
		Entry("2018-8-22", "2018-8-22"),
		Entry("2019-8-12", "2019-8-12"),
		Entry("2020-8-01", "2020-8-01"),
		Entry("2021-7-21", "2021-7-21"),
		Entry("2022-7-10", "2022-7-10"),
		Entry("2023-6-29", "2023-6-29"),
		Entry("2024-6-17", "2024-6-17"),
		Entry("2025-6-7", "2025-6-7"),
		Entry("2026-5-28", "2026-5-28"),
		Entry("2027-5-17", "2027-5-17"),
		Entry("2028-5-6", "2028-5-6"),
		Entry("2029-4-25", "2029-4-25"),
		Entry("2030-4-14", "2030-4-14"),
		Entry("2031-4-4", "2031-4-4"),
		Entry("2032-3-23", "2032-3-23"),
	)

	DescribeTable("012_KurbanBayramıÜçüncüTatil", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Kurban Bayramı (üçüncü tatil)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Kurban Bayramı (üçüncü tatil)", hols))
	},
		Entry("2017-9-3", "2017-9-3"),
		Entry("2018-8-23", "2018-8-23"),
		Entry("2019-8-13", "2019-8-13"),
		Entry("2020-8-02", "2020-8-02"),
		Entry("2021-7-22", "2021-7-22"),
		Entry("2022-7-11", "2022-7-11"),
		Entry("2023-6-30", "2023-6-30"),
		Entry("2024-6-18", "2024-6-18"),
		Entry("2025-6-8", "2025-6-8"),
		Entry("2026-5-29", "2026-5-29"),
		Entry("2027-5-18", "2027-5-18"),
		Entry("2028-5-7", "2028-5-7"),
		Entry("2029-4-26", "2029-4-26"),
		Entry("2030-4-15", "2030-4-15"),
		Entry("2031-4-5", "2031-4-5"),
		Entry("2032-3-24", "2032-3-24"),
	)

	DescribeTable("013_KurbanBayramıDördüncüTatil", func(s string) {
		opts := holidays.Options{Regions: []string{"tr"}}
		d, err := parseFlex(s)
		Expect(err).NotTo(HaveOccurred())
		hols, err := holidays.On(d, opts)
		Expect(err).NotTo(HaveOccurred())
		Expect(hasNamed(hols, "Kurban Bayramı (dördüncü tatil)")).To(BeTrue(), fmt.Sprintf("On(%s, %v): want holiday %q, got %v", s, opts.Regions, "Kurban Bayramı (dördüncü tatil)", hols))
	},
		Entry("2017-9-4", "2017-9-4"),
		Entry("2018-8-24", "2018-8-24"),
		Entry("2019-8-14", "2019-8-14"),
		Entry("2020-8-03", "2020-8-03"),
		Entry("2021-7-23", "2021-7-23"),
		Entry("2022-7-12", "2022-7-12"),
		Entry("2023-7-1", "2023-7-1"),
		Entry("2024-6-19", "2024-6-19"),
		Entry("2025-6-9", "2025-6-9"),
		Entry("2026-5-30", "2026-5-30"),
		Entry("2027-5-19", "2027-5-19"),
		Entry("2028-5-8", "2028-5-8"),
		Entry("2029-4-27", "2029-4-27"),
		Entry("2030-4-16", "2030-4-16"),
		Entry("2031-4-6", "2031-4-6"),
		Entry("2032-3-25", "2032-3-25"),
	)

})
