// Code generated by gen-holidays from definitions/ua.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var uaRules = []definition.HolidayRule{
	{
		Name:         "Великдень",
		Regions:      []string{"ua"},
		Month:        0,
		Wday:         -1,
		Function:     "orthodox_easter",
		FunctionArgs: []string{"year"},
		Observed:     "to_monday_if_weekend",
	},
	{
		Name:             "Трійця",
		Regions:          []string{"ua"},
		Month:            0,
		Wday:             -1,
		Function:         "orthodox_easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: 49,
		Observed:         "to_monday_if_weekend",
	},
	{
		Name:     "Новий Рік",
		Regions:  []string{"ua"},
		Month:    1,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:     "Різдво Христове",
		Regions:  []string{"ua"},
		Month:    1,
		Mday:     7,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:     "Міжнародний жіночий день",
		Regions:  []string{"ua"},
		Month:    3,
		Mday:     8,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:     "День праці",
		Regions:  []string{"ua"},
		Month:    5,
		Mday:     1,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:    "День міжнародної солідарності трудящих",
		Regions: []string{"ua"},
		Month:   5,
		Mday:    2,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeUntil, Years: []int{2017}},
		},
	},
	{
		Name:     "День перемоги над нацизмом у Другій світовій війні",
		Regions:  []string{"ua"},
		Month:    5,
		Mday:     9,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
	},
	{
		Name:     "День Конституції",
		Regions:  []string{"ua"},
		Month:    6,
		Mday:     28,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{1997}},
		},
	},
	{
		Name:    "День Незалежності України",
		Regions: []string{"ua"},
		Month:   7,
		Mday:    16,
		Wday:    -1,
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeLimited, Years: []int{1991}},
		},
	},
	{
		Name:     "День Незалежності",
		Regions:  []string{"ua"},
		Month:    8,
		Mday:     24,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{1992}},
		},
	},
	{
		Name:     "День захисника України",
		Regions:  []string{"ua"},
		Month:    10,
		Mday:     14,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2015}},
		},
	},
	{
		Name:     "Різдво Христове",
		Regions:  []string{"ua"},
		Month:    12,
		Mday:     25,
		Wday:     -1,
		Observed: "to_monday_if_weekend",
		YearRanges: []definition.YearRange{
			{Kind: definition.YearRangeFrom, Years: []int{2017}},
		},
	},
}

var uaRegionNames = map[string]string{
	"ua": "Ukraine",
}

func init() {
	engine.RegisterCountry("ua", uaRules)
	engine.RegisterRegionNames("ua", uaRegionNames)
}
