// Code generated by gen-holidays from definitions/ups.yaml@v9.0.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var upsRules = []definition.HolidayRule{
	{
		Name:     "New Year's Day",
		Regions:  []string{"ups"},
		Month:    1,
		Mday:     1,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
	{
		Name:    "Birthday of Martin Luther King, Jr",
		Regions: []string{"ups"},
		Month:   1,
		Wday:    1,
		Week:    3,
	},
	{
		Name:    "Memorial Day",
		Regions: []string{"ups"},
		Month:   5,
		Wday:    1,
		Week:    -1,
	},
	{
		Name:     "Independence Day",
		Regions:  []string{"ups"},
		Month:    7,
		Mday:     4,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
	{
		Name:    "Labor Day",
		Regions: []string{"ups"},
		Month:   9,
		Wday:    1,
		Week:    1,
	},
	{
		Name:    "Thanksgiving",
		Regions: []string{"ups"},
		Month:   11,
		Wday:    4,
		Week:    4,
	},
	{
		Name:         "Day After Thanksgiving",
		Regions:      []string{"ups"},
		Month:        11,
		Wday:         -1,
		Function:     "day_after_thanksgiving",
		FunctionArgs: []string{"year"},
	},
	{
		Name:     "Christmas Day",
		Regions:  []string{"ups"},
		Month:    12,
		Mday:     25,
		Wday:     -1,
		Observed: "to_weekday_if_weekend",
	},
	{
		Name:    "New Year's Eve",
		Regions: []string{"ups"},
		Month:   12,
		Mday:    31,
		Wday:    -1,
	},
}

var upsRegionNames = map[string]string{
	"ups": "UPS",
}

func init() {
	engine.RegisterCountry("ups", upsRules)
	engine.RegisterRegionNames("ups", upsRegionNames)
}
