// Code generated by gen-holidays from definitions/ve.yaml@v9.1.0. DO NOT EDIT.

package definitions

import (
	"github.com/holidays/go-holidays/internal/definition"
	"github.com/holidays/go-holidays/internal/engine"
)

var veRules = []definition.HolidayRule{
	{
		Name:             "Lunes Carnaval",
		Regions:          []string{"ve"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -48,
	},
	{
		Name:             "Martes Carnaval",
		Regions:          []string{"ve"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -47,
	},
	{
		Name:             "Jueves Santo",
		Regions:          []string{"ve"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -3,
	},
	{
		Name:             "Viernes Santo",
		Regions:          []string{"ve"},
		Month:            0,
		Wday:             -1,
		Function:         "easter",
		FunctionArgs:     []string{"year"},
		FunctionModifier: -2,
	},
	{
		Name:    "Año Nuevo",
		Regions: []string{"ve"},
		Month:   1,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Declaración Independencia",
		Regions: []string{"ve"},
		Month:   4,
		Mday:    19,
		Wday:    -1,
	},
	{
		Name:    "Día del Trabajador",
		Regions: []string{"ve"},
		Month:   5,
		Mday:    1,
		Wday:    -1,
	},
	{
		Name:    "Aniversario Batalla de Carabobo",
		Regions: []string{"ve"},
		Month:   6,
		Mday:    24,
		Wday:    -1,
	},
	{
		Name:    "Día de la Independencia",
		Regions: []string{"ve"},
		Month:   7,
		Mday:    5,
		Wday:    -1,
	},
	{
		Name:    "Natalicio de Simón Bolívar",
		Regions: []string{"ve"},
		Month:   7,
		Mday:    24,
		Wday:    -1,
	},
	{
		Name:    "Día de la Resistencia Indígena",
		Regions: []string{"ve"},
		Month:   10,
		Mday:    12,
		Wday:    -1,
	},
	{
		Name:    "Día de Navidad",
		Regions: []string{"ve"},
		Month:   12,
		Mday:    25,
		Wday:    -1,
	},
}

var veRegionNames = map[string]string{
	"ve": "Venezuela",
}

func init() {
	engine.RegisterCountry("ve", veRules)
	engine.RegisterRegionNames("ve", veRegionNames)
}
